---
sidebar: sidebar 
permalink: concept-agents.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is an agent required, agent supported locations, restricted mode, private mode, dark site, permissions, multiple agents, disaster recovery, agents, multiple agents, what is a Console agent' 
summary: Sie verwenden einen Console-Agenten, um die NetApp Console mit Ihrer Infrastruktur zu verbinden und Speicherlösungen sicher über AWS-, Azure-, Google Cloud- oder On-Premises-Umgebungen hinweg zu orchestrieren sowie Datensicherungsdienste zu nutzen. 
---
= Erfahren Sie mehr über NetApp Console -Agenten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie verwenden einen Console-Agenten, um die NetApp Console mit Ihrer Infrastruktur zu verbinden und Speicherlösungen sicher über AWS-, Azure-, Google Cloud- oder On-Premises-Umgebungen hinweg zu orchestrieren sowie Datensicherungsdienste zu nutzen.

Ein Konsolenagent ermöglicht Ihnen Folgendes:

* Orchestrieren Sie Speicherverwaltungsaufgaben über die NetApp Console , wie z. B. die Bereitstellung von Cloud Volumes ONTAP, das Einrichten von Speichervolumes, die Verwendung der Datenklassifizierung und vieles mehr.
* Authentifizieren Sie sich mithilfe der IAM-Rollen Ihres Cloud-Anbieters für die Integration der Abonnementabrechnung.
* Nutzen Sie erweiterte Datendienste (NetApp Backup and Recovery, NetApp Disaster Recovery, NetApp Ransomware Resilience und NetApp Cloud Tiering).


Wenn Sie keine erweiterten Orchestrierungs- oder Datenschutzdienste benötigen, können Sie lokale ONTAP-Cluster und Cloud-native Speicherdienste zentral verwalten, ohne einen Agenten bereitzustellen. Einige Überwachungs- und Datenmobilitätstools sind ebenfalls ohne Agenten verfügbar.

Die folgende Tabelle zeigt, welche Funktionen und Dienste Sie mit und ohne Console-Agent nutzen können.

[cols="40,20a,20a"]
|===
|  | Beim Agenten erhältlich | Ohne Makler erhältlich 


3+| *Unterstützte Speichersysteme*: 


| Amazon FSx für ONTAP  a| 
Ja (Erkennungs- und Verwaltungsfunktionen)
 a| 
Ja (nur Discovery)



| Amazon S3-Speicher  a| 
Ja
 a| 
Nein



| Azure Blob-Speicher  a| 
Ja
 a| 
Ja



| Azure NetApp Files  a| 
Ja
 a| 
Ja



| Cloud Volumes ONTAP  a| 
Ja
 a| 
Nein



| Systeme der E-Serie  a| 
Ja
 a| 
Nein



| Google Cloud NetApp Volumes  a| 
Ja
 a| 
Ja



| Google Cloud-Speicher-Buckets  a| 
Ja
 a| 
Nein



| StorageGRID -Systeme  a| 
Ja
 a| 
Nein



| On-Premises ONTAP Cluster (erweiterte Verwaltung und Erkennung)  a| 
Ja (fortschrittliches Management und Entdeckung)
 a| 
Nein (nur grundlegende Entdeckung)



3+| *Storage-Management und Gesundheitsdienste*: 


| Warnungen  a| 
Ja
 a| 
Nein



| Automatisierungszentrum  a| 
Ja
 a| 
Ja



| Digital Advisor (Active IQ)  a| 
Ja
 a| 
Nein



| Lizenz- und Abonnementverwaltung  a| 
Ja
 a| 
Nein



| Wirtschaftlichkeit  a| 
Ja
 a| 
Nein



| Dashboard-Metriken der Startseite  a| 
Ja^2^
 a| 
Nein



| Lebenszyklusplanung  a| 
Ja
 a| 
Nr. 1



| Nachhaltigkeit  a| 
Ja
 a| 
Nein



| Software-Updates  a| 
Ja
 a| 
Ja



| NetApp Workloads  a| 
Ja
 a| 
Ja



3+| *Verfügbare Datendienste*: 


| NetApp Backup and Recovery  a| 
Ja
 a| 
Nein



| NetApp Data Classification  a| 
Ja
 a| 
Nein



| NetApp Cloud Tiering  a| 
Ja
 a| 
Nein



| NetApp Copy and Sync  a| 
Ja
 a| 
Nein



| NetApp Disaster Recovery  a| 
Ja
 a| 
Nein



| NetApp Ransomware Resilience  a| 
Ja
 a| 
Nein



| NetApp Volume Caching  a| 
Ja
 a| 
Nein

|===
^1^ Die Lebenszyklusplanung kann auch ohne Konsolenagent angezeigt werden, jedoch ist ein Konsolenagent erforderlich, um Aktionen auszulösen.

^2^ Für genaue Messwerte auf der Startseite sind entsprechend dimensionierte und konfigurierte Konsolenagenten erforderlich.



== Konsolenagenten müssen jederzeit betriebsbereit sein

Konsolenagenten sind ein grundlegender Bestandteil der NetApp Console.  Es liegt in Ihrer Verantwortung (des Kunden), sicherzustellen, dass die relevanten Agenten jederzeit aktiv, betriebsbereit und erreichbar sind.  Die Konsole kann kurze Agentenausfälle bewältigen, Infrastrukturfehler müssen Sie jedoch schnell beheben.

Diese Dokumentation unterliegt der EULA.  Der Betrieb des Produkts außerhalb der Dokumentation kann seine Funktionalität und Ihre EULA-Rechte beeinträchtigen.



== Unterstützte Standorte

Sie können Agenten an den folgenden Orten installieren:

* Amazon Web Services
* Microsoft Azure
+
Stellen Sie einen Konsolenagenten in Azure in derselben Region bereit wie die von ihm verwalteten Cloud Volumes ONTAP -Systeme.  Alternativ können Sie es in der https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure-Regionenpaar"^] .  Dadurch wird sichergestellt, dass zwischen Cloud Volumes ONTAP und den zugehörigen Speicherkonten eine Azure Private Link-Verbindung verwendet wird. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-enabling-private-link.html["Erfahren Sie, wie Cloud Volumes ONTAP einen Azure Private Link verwendet"^]

* Google Cloud
+
Um die Konsole und Datendienste mit Google Cloud zu verwenden, stellen Sie Ihren Agenten in Google Cloud bereit.

* Bei Ihnen vor Ort




== Kommunikation mit Cloud-Anbietern

Der Agent verwendet TLS 1.3 für die gesamte Kommunikation mit AWS, Azure und Google Cloud.



== So installieren Sie einen Konsolenagenten

Sie können einen Konsolenagenten direkt von der Konsole, vom Marktplatz Ihres Cloud-Anbieters oder durch manuelle Installation der Software auf Ihrem eigenen Linux-Host oder in Ihrer VCenter-Umgebung installieren.

* link:concept-modes.html["Erfahren Sie mehr über die Bereitstellungsmodi der NetApp Console"]
* link:task-quick-start-standard-mode.html["Erste Schritte mit der NetApp Console im Standardmodus"]
* link:task-quick-start-restricted-mode.html["Erste Schritte mit der NetApp Console im eingeschränkten Modus"]




== Cloud-Anbieter-Berechtigungen

Sie benötigen spezielle Berechtigungen, um den Konsolenagenten direkt von der NetApp Console aus zu erstellen, und einen weiteren Satz von Berechtigungen für den Konsolenagenten selbst. Wenn Sie den Konsolenagenten in AWS oder Azure direkt von der Konsole aus erstellen, erstellt die Konsole den Konsolenagenten mit den erforderlichen Berechtigungen.

Wenn Sie die Konsole im Standardmodus verwenden, hängt die Art und Weise, wie Sie Berechtigungen erteilen, davon ab, wie Sie den Konsolenagenten erstellen möchten.

Informationen zum Einrichten von Berechtigungen finden Sie hier:

* Standardmodus
+
** link:concept-install-options-aws.html["Agent-Installationsoptionen in AWS"]
** link:concept-install-options-azure.html["Agent-Installationsoptionen in Azure"]
** link:concept-install-options-google.html["Agent-Installationsoptionen in Google Cloud"]
** link:task-install-agent-on-prem.html#agent-permission-aws-azure["Einrichten von Cloudberechtigungen für lokale Bereitstellungen"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Berechtigungen für den eingeschränkten Modus einrichten"]


Informationen zu den genauen Berechtigungen, die der Konsolenagent für den täglichen Betrieb benötigt, finden Sie auf den folgenden Seiten:

* link:reference-permissions-aws.html["Erfahren Sie, wie der Konsolenagent AWS-Berechtigungen verwendet"]
* link:reference-permissions-azure.html["Erfahren Sie, wie der Konsolen-Agent Azure-Berechtigungen verwendet."]
* link:reference-permissions-gcp.html["Erfahren Sie, wie der Konsolenagent Google Cloud-Berechtigungen verwendet"]


Es liegt in Ihrer Verantwortung, die Richtlinien des Konsolenagenten zu aktualisieren, wenn in nachfolgenden Versionen neue Berechtigungen hinzugefügt werden.  In den Versionshinweisen sind neue Berechtigungen aufgeführt.



== Agent-Upgrades

NetApp aktualisiert die Agentensoftware monatlich, um Funktionen hinzuzufügen und die Stabilität zu verbessern.  Einige Konsolenfunktionen, wie Cloud Volumes ONTAP und die lokale ONTAP Clusterverwaltung, basieren auf der Version und den Einstellungen des Konsolenagenten.

Wenn Sie Ihren Agenten in der Cloud installieren, aktualisiert sich der Console-Agent automatisch, sofern er über einen Internetzugang verfügt.



== Betriebssystem- und VM-Wartung

Die Wartung des Betriebssystems auf dem Konsolenagent-Host liegt in Ihrer (Kunden-)Verantwortung.  Beispielsweise sollten Sie (der Kunde) Sicherheitsupdates auf das Betriebssystem auf dem Konsolenagent-Host anwenden, indem Sie die Standardverfahren Ihres Unternehmens zur Betriebssystemverteilung befolgen.

Beachten Sie, dass Sie (der Kunde) beim Anwenden kleinerer Sicherheitsupdates keine Dienste auf dem Console Gent-Host stoppen müssen.

Wenn Sie (der Kunde) die Konsolen-Agent-VM stoppen und dann starten müssen, sollten Sie dies über die Konsole Ihres Cloud-Anbieters oder mithilfe der Standardverfahren für die lokale Verwaltung tun.

<<agents-must-be-operational-at-all-times,Der Konsolenagent muss jederzeit betriebsbereit sein>> .



== Mehrere Systeme und Agenten

Ein Agent kann mehrere Systeme verwalten und Datendienste in der Konsole unterstützen.  Sie können einen einzelnen Agenten verwenden, um mehrere Systeme basierend auf der Bereitstellungsgröße und den von Ihnen verwendeten Datendiensten zu verwalten.

Arbeiten Sie bei groß angelegten Bereitstellungen mit Ihrem NetApp -Vertreter zusammen, um die Größe Ihrer Umgebung festzulegen.  Wenden Sie sich bei Problemen an den NetApp -Support.

Hier sind einige Beispiele für Agentenbereitstellungen:

* Sie verfügen über eine Multicloud-Umgebung (z. B. AWS und Azure) und möchten lieber einen Agenten in AWS und einen anderen in Azure haben.  Jedes verwaltet die in diesen Umgebungen ausgeführten Cloud Volumes ONTAP -Systeme.
* Ein Dienstanbieter könnte eine Konsolenorganisation nutzen, um seinen Kunden Dienste bereitzustellen, während er eine andere Organisation für die Notfallwiederherstellung einer seiner Geschäftseinheiten nutzt.  Jede Organisation benötigt ihren eigenen Agenten.

