---
sidebar: sidebar 
permalink: concept-verified-organization.html 
keywords: verified organization, organization verification, cmat, crm id, business account, identity and access management, iam, organization governance 
summary: Verifizierte Organisationen verknüpfen Ihre NetApp Console-Organisation mit Ihrem NetApp Geschäftskonto, sodass Identität und Governance systemübergreifend einheitlich sind. 
---
= Erfahren Sie mehr über verifizierte Organisationen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Eine verifizierte Organisation verknüpft Ihre Organisation in der NetApp Console mit Ihrer NetApp Geschäftskontoidentität (z. B. einer CMAT ID). Dies trägt dazu bei, dass die Console ein einheitliches Organisationsidentitäts- und Governance-Modell über NetApp Systeme hinweg anwendet.



== Warum Ihre Organisation verifizieren

Die Überprüfung Ihrer Organisation kann Ihnen helfen:

* Richten Sie Ihre Konsolenorganisation an der Identität Ihres NetApp Geschäftskontos aus.
* Verbessern Sie die Konsistenz für Administration, Berichterstellung und Support-Workflows.
* Verringern Sie Unklarheiten, wenn Ihre Teams mit mehreren NetApp Services zusammenarbeiten.
* Unterstützen Sie Governance-Kontrollen, die auf einer vertrauenswürdigen Organisationsidentität basieren.




== Was ändert sich nach der Überprüfung

Nach der Verifizierung Ihrer Organisation:

* Die Organisation ist mit einer NetApp Geschäftskontoidentität verknüpft.
* Die Konsole kann diese Organisationsidentität als maßgebend für die Zuordnung auf Geschäftsebene behandeln.
* Einige Änderungen am Organisationsprofil sind in der Konsole möglicherweise eingeschränkt, wenn sie vom Quellsystem verwaltet werden.




== Bevor Sie überprüfen

Bevor Sie Ihre Organisation verifizieren, bestätigen Sie Folgendes:

* Sie verfügen über die erforderliche administrative Rolle für Ihre Organisation.
* Sie verfügen über die für die Verifizierung erforderlichen Organisationsdaten.
* Sie haben sich mit Ihrem NetApp Account-Team abgestimmt, falls die Zuordnung von Geschäftskonten einer Validierung bedarf.




== Ähnliche Informationen

* link:task-verify-organization.html["Bestätigen Sie Ihre Organisation"]
* link:concept-identity-and-access-management.html["Erfahren Sie mehr über Identitäts- und Zugriffsverwaltung"]
* link:task-iam-rename-organization.html["Organisations- und Projekt-IDs"]

