---
settings:
  name: NetApp Console setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Einrichtung und Verwaltung der NetApp Konsole
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
    - title: Änderungen an unterstützten Linux-Betriebssystemen
      url: "/reference-connector-operating-system-changes.html"
  - title: Erste Schritte
    entries:
    - title: Lernen Sie die Grundlagen
      entries:
      - title: NetApp Konsole
        url: "/concept-overview.html"
      - title: Konsolenagenten
        url: "/concept-connectors.html"
      - title: Bereitstellungsmodi
        url: "/concept-modes.html"
    - title: Erste Schritte mit dem NetApp Console-Assistenten
      entries:
      - title: Verwenden Sie den NetApp Console-Assistenten
        url: "/task-console-assistant.html"
    - title: Erste Schritte mit dem Standardmodus
      entries:
      - title: Workflow „Erste Schritte“
        url: "/task-quick-start-standard-mode.html"
      - title: Netzwerkzugriff für die NetApp -Konsole vorbereiten
        url: "/reference-networking-saas-console.html"
      - title: Bei der NetApp Konsole anmelden
        url: "/task-sign-up-saas.html"
      - title: Erstellen eines Konsolenagenten
        entries:
        - title: AWS
          entries:
          - title: Installationsoptionen für den Konsolenagenten
            url: "/concept-install-options-aws.html"
          - title: Erstellen Sie einen Konsolenagenten über die NetApp Konsole
            url: "/task-install-connector-aws-bluexp.html"
          - title: Erstellen Sie einen Konsolenagenten aus dem Marktplatz
            url: "/task-install-connector-aws-marketplace.html"
          - title: Manuelle Installation des Konsolenagenten
            url: "/task-install-connector-aws-manual.html"
        - title: Azurblau
          entries:
          - title: Installationsoptionen für den Konsolenagenten
            url: "/concept-install-options-azure.html"
          - title: Erstellen Sie einen Konsolenagenten über die NetApp Konsole
            url: "/task-install-connector-azure-bluexp.html"
          - title: Erstellen Sie einen Konsolenagenten aus dem Marktplatz
            url: "/task-install-connector-azure-marketplace.html"
          - title: Manuelle Installation des Konsolenagenten
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Installationsoptionen für den Konsolenagenten
            url: "/concept-install-options-google.html"
          - title: Erstellen Sie einen Konsolenagenten über die NetApp Konsole
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Erstellen Sie einen Konsolenagenten aus Google Cloud
            url: "/task-install-agent-google-gcloud.html"
          - title: Manuelle Installation des Konsolenagenten
            url: "/task-install-connector-google-manual.html"
        - title: Installieren eines Agenten vor Ort
          entries:
          - title: Manuelles Installieren eines Agenten vor Ort
            url: "/task-install-connector-on-prem.html"
          - title: Installieren Sie einen lokalen Agenten in VCenter
            url: "/task-install-agent-on-prem-ova.html"
      - title: Abonnieren Sie NetApp Intelligent Services
        url: "/task-subscribe-standard-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next.html"
    - title: Erste Schritte mit dem eingeschränkten Modus
      entries:
      - title: Workflow „Erste Schritte“
        url: "/task-quick-start-restricted-mode.html"
      - title: Vorbereiten der Bereitstellung
        url: "/task-prepare-restricted-mode.html"
      - title: Bereitstellen des Konsolenagenten
        url: "/task-install-restricted-mode.html"
      - title: Abonnieren Sie NetApp Intelligent Services
        url: "/task-subscribe-restricted-mode.html"
      - title: Was Sie als Nächstes tun können
        url: "/reference-whats-next-restricted-mode.html"
    - title: Erste Schritte mit der BlueXP -Legacy-Schnittstelle (privater Modus)
      entries:
      - title: Erste Schritte mit der BlueXP -Legacy-Schnittstelle (privater Modus)
        url: "/task-quick-start-private-mode.html"
  - title: Verwenden Sie die NetApp Konsole
    entries:
    - title: Melden Sie sich bei der NetApp Konsole an
      url: "/task-logging-in.html"
    - title: Anzeigen von Metriken auf der Startseite der NetApp Konsole
      url: "/task-dashboard.html"
    - title: Verwalten Sie Ihre NetApp -Konsolenbenutzereinstellungen
      url: "/task-user-settings.html"
  - title: NetApp -Konsole verwalten
    entries:
    - title: Identitäts- und Zugriffsverwaltung
      entries:
      - title: Erfahren Sie mehr über die Verwaltung von Identität und Zugriff
        url: "/concept-identity-and-access-management.html"
      - title: Erste Schritte mit Identität und Zugriff
        url: "/task-iam-get-started.html"
      - title: Organisieren Sie Ihre Ressourcen mit Ordnern und Projekten
        url: "/task-iam-manage-folders-projects.html"
      - title: Mitglieder und Dienstkonten verwalten
        url: "/task-iam-manage-members-permissions.html"
      - title: Verwenden Sie Rollen, um den Zugriff der Mitglieder auf Ressourcen
          zu steuern
        url: "/task-iam-manage-roles.html"
      - title: Verwalten Sie Ihre Ressourcenhierarchie
        url: "/task-iam-manage-resources.html"
      - title: Verknüpfen Sie einen Konsolenagenten mit anderen Ordnern und Projekten
        url: "/task-iam-associate-connectors.html"
      - title: Wechseln Sie zwischen Organisationen, Projekten und Konsolenagenten
        url: "/task-iam-switch-organizations-projects.html"
      - title: Organisations- und Projekt-IDs
        url: "/task-iam-rename-organization.html"
      - title: Überwachen oder prüfen Sie die IAM-Aktivität
        url: "/task-iam-audit-actions-timeline.html"
      - title: NetApp -Konsolenzugriffsrollen
        entries:
        - title: Erfahren Sie mehr über die Zugriffsrollen der NetApp Konsole
          url: "/reference-iam-predefined-roles.html"
        - title: Plattformrollen
          url: "/reference-iam-platform-roles.html"
        - title: Anwendungsrollen
          entries:
          - title: Google Cloud NetApp Volumes Rollen
            url: "/reference-iam-gcnv-roles.html"
          - title: Keystone
            url: "/reference-iam-keystone-roles.html"
          - title: Betriebsunterstützungsanalyst
            url: "/reference-iam-analyst-roles.html"
          - title: Speicherrollen
            url: "/reference-iam-storage-roles.html"
        - title: Datendienstrollen
          entries:
          - title: Sicherungs- und Wiederherstellungsrollen
            url: "/reference-iam-backup-rec-roles.html"
          - title: Rollen für die Notfallwiederherstellung
            url: "/reference-iam-disaster-rec-roles.html"
          - title: Rollen zum Schutz vor Ransomware
            url: "/reference-iam-ransomware-roles.html"
    - title: Partnerorganisationen
      entries:
      - title: Erfahren Sie mehr über Organisationspartnerschaften
        url: "/concept-org-partnerships.html"
      - title: Erstellen Sie eine Organisationspartnerschaft
        url: "/task-partnerships-create.html"
      - title: Mitglieder für eine Partnerschaftsorganisation verwalten
        url: "/task-partnerships-assign-users.html"
      - title: Verwalten des Ressourcenzugriffs für eine Partnerschaftsorganisation
        url: "/task-partnerships-resource-access.html"
      - title: Arbeit in einer Partnerorganisation
        url: "/task-partnerships-work.html"
    - title: Identitätsföderation
      entries:
      - title: Erfahren Sie mehr über die Identitätsföderation
        url: "/concept-federation.html"
      - title: Domänenüberprüfung
        entries:
        - title: Bestätigen Sie Ihre Domäne
          url: "/task-federation-verify-domain.html"
      - title: Konfigurieren von Föderationen
        entries:
        - title: Verbund mit einem Active Directory Federation Services (AD FS)-Anbieter
          url: "/task-federation-adfs.html"
        - title: Verbund mit dem Microsoft Entra ID-Anbieter
          url: "/task-federation-entra-id.html"
        - title: Föderieren Sie mit PingFederate
          url: "/task-federation-ping.html"
        - title: Föderieren Sie mit einem SAML-Identitätsanbieter
          url: "/task-federation-saml.html"
      - title: Föderationen verwalten
        url: "/task-federation-manage.html"
      - title: Importieren Sie Ihre vorhandene Verbundverbindung
        url: "/task-federation-import.html"
    - title: Konsolenagenten
      entries:
      - title: Wartung der VM und des Betriebssystems
        url: "/task-maintain-connectors.html"
      - title: Verwalten eines in VCenter installierten Agenten
        url: "/task-agent-vm-config.html"
      - title: Installieren Sie ein CA-signiertes Zertifikat für den Zugriff auf die
          Webkonsole
        url: "/task-installing-https-cert.html"
      - title: Konfigurieren eines Konsolenagenten zur Verwendung eines Proxyservers
        url: "/task-configuring-proxy.html"
      - title: Erfordert die Verwendung von IMDSv2 auf EC2-Instanzen
        url: "/task-require-imdsv2.html"
      - title: Connector-Upgrades verwalten
        url: "/task-upgrade-connector.html"
      - title: Arbeiten mit mehreren Konsolenagenten
        url: "/task-manage-multiple-connectors.html"
      - title: Fehlerbehebung beim Konsolen-Agent
        url: "/task-troubleshoot-agent.html"
      - title: Deinstallieren und entfernen Sie den Konsolenagenten
        url: "/task-uninstall-connector.html"
      - title: Standardkonfiguration
        url: "/reference-connector-default-config.html"
      - title: Erzwingen Sie ONTAP -Berechtigungen in der NetApp Konsole
        url: "/task-ontap-access-connector.html"
    - title: Anmeldeinformationen und Abonnements
      entries:
      - title: AWS
        entries:
        - title: Erfahren Sie mehr über Anmeldeinformationen und Berechtigungen
          url: "/concept-accounts-aws.html"
        - title: Verwalten von Anmeldeinformationen und Abonnements
          url: "/task-adding-aws-accounts.html"
      - title: Azurblau
        entries:
        - title: Erfahren Sie mehr über Anmeldeinformationen und Berechtigungen
          url: "/concept-accounts-azure.html"
        - title: Verwalten von Anmeldeinformationen und Abonnements
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Erfahren Sie mehr über Projekte und Berechtigungen
          url: "/concept-accounts-gcp.html"
        - title: Verwalten von Anmeldeinformationen und Abonnements
          url: "/task-adding-gcp-accounts.html"
      - title: Verwalten Sie NSS-Anmeldeinformationen, die einer NetApp Console-Organisation
          oder einem NetApp Console-Konto zugeordnet sind
        url: "/task-adding-nss-accounts.html"
      - title: Verwalten Sie die mit Ihrer NetApp Konsolenanmeldung verknüpften Anmeldeinformationen
        url: "/task-manage-user-credentials.html"
    - title: Überwachen Sie NetApp -Konsolenvorgänge
      url: "/task-monitor-cm-operations.html"
  - title: Referenz
    entries:
    - title: Agenten-Wartungskonsole
      entries:
      - title: Agenten-Wartungskonsole
        url: "/reference-connector-maint-console.html"
    - title: Berechtigungen
      entries:
      - title: Zusammenfassung der Berechtigungen
        url: "/reference-permissions.html"
      - title: AWS-Berechtigungen für den Konsolenagenten
        url: "/reference-permissions-aws.html"
      - title: Azure-Berechtigungen für den Konsolen-Agent
        url: "/reference-permissions-azure.html"
      - title: Google Cloud-Berechtigungen für den Konsolenagenten
        url: "/reference-permissions-gcp.html"
    - title: Häfen
      entries:
      - title: Sicherheitsgruppenregeln für Konsolenagenten in AWS
        url: "/reference-ports-aws.html"
      - title: Sicherheitsgruppenregeln für Konsolen-Agents in Azure
        url: "/reference-ports-azure.html"
      - title: Firewallregeln für Konsolenagenten in Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Ports für den lokalen Konsolenagenten
        url: "/reference-ports-on-prem.html"
    - title: Konsolennetzwerkzugriff (Legacy)
      url: "/reference-networking-saas-console-previous.html"
  - title: Wissen und Unterstützung
    entries:
    - title: Für Support registrieren
      url: "/task-support-registration.html"
    - title: Hilfe erhalten
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
