---
sidebar: sidebar 
permalink: reference-iam-data-classification.html 
keywords: role-based access control, IAM roles, access delegation, data classification, cloud data sense, compliance admin, classification viewer 
summary: NetApp Data Classification unterstützt zwei Rollen zur Verwaltung des Lese- und Schreibzugriffs auf Assets. 
---
= NetApp Data Classification-Rollen in der NetApp Console
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification unterstützt Rollen für Identitäts- und Zugriffsmanagement (IAM), sodass Sie den Zugriff an die Aufgaben anpassen können, die Benutzer erledigen müssen. Wie Sie Rollen zuweisen, hängt von Ihren eigenen Geschäfts- und Speichermanagementpraktiken ab.

Data Classification unterstützt zwei Rollen:

* Compliance-Admin
* Klassifizierungsanzeige




[[compliance-admin]]
== Compliance-Admin

Die Rolle des Compliance-Administrators dient ausschließlich auf Organisationsebene zur Verwaltung des Zugriffs auf Data Classification-Ressourcen. Wenn ein Benutzer weniger Verantwortlichkeiten als ein Organisationsadministrator hat, muss er die Rolle des Compliance-Administrators haben, um Data Classification zu installieren.


IMPORTANT: Die Rolle des Compliance-Administrators ist keine eigenständige Rolle. Benutzer mit der Rolle des Compliance-Administrators müssen auch mindestens einer link:reference-iam-platform-roles.html["Plattformrolle"] zugeordnet sein.


NOTE: The Compliance admin wurde in Version 1.54 zu Data Classification hinzugefügt. Wenn Sie Data Classification vor dieser Version bereitgestellt hatten und eine Plattformrolle mit weniger Zugriffsrechten als ein Organization admin hatten, wurde die Compliance admin-Rolle automatisch dem Benutzerkonto zugeordnet.



[[classification-viewer]]
== Klassifizierungsanzeige

Der Classification Viewer ist für Benutzer konzipiert, die Zugriff auf Scan-Ergebnisse in NetApp Data Classification benötigen, jedoch keinen Zugriff auf Konfigurationsressourcen. Benutzer mit der Rolle Classification Viewer können die Ergebnisse von Mapping- und vollständigen Scans einsehen, um Bereiche mit Speichereinsparungen oder potenziellen Datenrisiken zu beurteilen. Benutzer mit der Rolle Classification Viewer können außerdem Berichte für Ressourcen generieren, auf die sie Zugriff haben. Diese Benutzer können das Scannen von Volumes, Buckets oder Datenbank-Schemas nicht aktivieren oder deaktivieren.



[[more-information]]
== Weitere Informationen

* link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["Erfahren Sie mehr über NetApp Data Classification"^]

