---
sidebar: sidebar 
permalink: reference-ports-aws.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: Die AWS-Sicherheitsgruppe für den Konsolenagenten erfordert sowohl eingehende als auch ausgehende Regeln.  Die NetApp Console erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Konsolenagenten von der Konsole aus erstellen.  Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten. 
---
= Sicherheitsgruppenregeln für Konsolenagenten in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die AWS-Sicherheitsgruppe für den Agenten erfordert sowohl eingehende als auch ausgehende Regeln.  Die NetApp Console erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Konsolenagenten von der Konsole aus erstellen.  Sie müssen diese Sicherheitsgruppe für alle anderen Installationsoptionen einrichten.



== Eingehende Regeln

[cols="10,10,80"]
|===
| Protokoll | Hafen | Zweck 


| SSH | 22 | Bietet SSH-Zugriff auf den Agent-Host 


| HTTP | 80  a| 
* Bietet HTTP-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche
* Wird während des Upgrade-Prozesses von Cloud Volumes ONTAP verwendet




| HTTPS | 443 | Bietet HTTPS-Zugriff auf die lokale Benutzeroberfläche und Verbindungen von der NetApp Data Classification Instanz 


| TCP | 3128 | Bietet Cloud Volumes ONTAP Internetzugang.  Sie müssen diesen Port nach der Bereitstellung manuell öffnen. 
|===


== Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für den Agenten öffnet den gesamten ausgehenden Datenverkehr.  Wenn das akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Nachrichten.  Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Ausgangsregeln.



=== Grundlegende Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für den Agenten umfasst die folgenden ausgehenden Regeln.

[cols="20,20,60"]
|===
| Protokoll | Hafen | Zweck 


| Alle TCP | Alle | Der gesamte ausgehende Verkehr 


| Alle UDP | Alle | Der gesamte ausgehende Verkehr 
|===


=== Erweiterte Ausgangsregeln

Wenn Sie strenge Regeln für den ausgehenden Verkehr benötigen, können Sie die folgenden Informationen verwenden, um nur die Ports zu öffnen, die für die ausgehende Kommunikation durch den Agenten benötigt werden


NOTE: Die Quell-IP-Adresse ist der Agent-Host.

[cols="5*"]
|===
| Service | Protokoll | Hafen | Ziel | Zweck 


| API-Aufrufe und AutoSupport | HTTPS | 443 | Outbound-Internet und ONTAP Cluster-Management-LIF | API-Aufrufe an AWS, ONTAP, NetApp Data Classification und Senden von AutoSupport -Nachrichten an NetApp 


.2+| API-Aufrufe | TCP | 3000 | ONTAP HA-Mediator | Kommunikation mit dem ONTAP HA Mediator 


| TCP | 8080 | Datenklassifizierung | Testen der Datenklassifizierungsinstanz während der Bereitstellung 


| DNS | UDP | 53 | DNS | Wird von der Konsole für die DNS-Auflösung verwendet 
|===