---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: NetApp Console, der NetApp Console-Agent und NetApp Datendienste erfordern ausgehenden Internetzugang und die Möglichkeit, die erforderlichen Endpunkte zu kontaktieren. 
---
= Netzwerkzugriff für die NetApp -Konsole vorbereiten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, der NetApp Console-Agent und NetApp Datendienste erfordern ausgehenden Internetzugang und die Möglichkeit, die erforderlichen Endpunkte zu kontaktieren.

Sie müssen den Netzwerkzugriff für Folgendes einrichten:

* Computer, die als Software as a Service (SaaS) auf die NetApp Konsole zugreifen
* Netzwerkstandorte, an denen Sie Konsolenagenten bereitstellen, die Sie vor Ort oder in der Cloud installieren.
* Zusätzliche Endpunkte für bestimmte NetApp -Datendienste, einschließlich Cloud Volumes ONTAP.



NOTE: NetApp hat die erforderlichen Netzwerkendpunkte für die Konsole und Konsolenagenten reduziert, wodurch die Sicherheit verbessert und die Bereitstellung vereinfacht wird.  Wichtig ist, dass alle Bereitstellungen vor Version 4.0.0 weiterhin vollständig unterstützt werden.  Während vorherige Endpunkte für vorhandene Agenten weiterhin verfügbar bleiben, empfiehlt NetApp dringend, die Firewall-Regeln auf die aktuellen Endpunkte zu aktualisieren, nachdem die erfolgreichen Agent-Upgrades bestätigt wurden.link:reference-networking-saas-console-previous.html["Erfahren Sie, wie Sie Ihre Endpunktliste aktualisieren."]



== Von der NetApp Konsole kontaktierte Endpunkte

Jeder Computer, der auf die NetApp Konsole zugreift, muss über Verbindungen zu den unten aufgeführten Endpunkten verfügen.

Das System kontaktiert diese Endpunkte in zwei Szenarien:

* Von einem Computer aus, der auf die https://console.netapp.com["NetApp Konsole"^] als Software as a Service (SaaS).
* Von einem Computer aus, der direkt auf einen Konsolen-Agent-Host zugreift, entweder um sich anzumelden und ihn einzurichten oder um vom Agent-Host aus auf die Konsole zuzugreifen.


[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://mysupport.netapp.com | Um Lizenzinformationen zu erhalten und AutoSupport -Nachrichten an den NetApp Support zu senden. 


| \https://support.netapp.com | Um Lizenzinformationen zu erhalten und AutoSupport -Nachrichten an den NetApp Support zu senden. 


| \https://signin.b2c.netapp.com | So aktualisieren Sie die Anmeldeinformationen der NetApp Support Site (NSS) oder fügen der NetApp Konsole neue NSS-Anmeldeinformationen hinzu. 


| \https:\\support.netapp.com | Zum Abrufen von Lizenzinformationen und zum Senden von AutoSupport -Nachrichten an den NetApp Support sowie zum Empfangen von Software-Updates für Cloud Volumes ONTAP. 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.bluexp.netapp.com \https://cdn.auth0.com | Zur Bereitstellung von Funktionen und Diensten innerhalb der NetApp Konsole. 


 a| 
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io
 a| 
Um Bilder für Upgrades des Konsolenagenten zu erhalten.

* Wenn Sie einen neuen Agenten bereitstellen, testet die Validierungsprüfung die Konnektivität zu aktuellen Endpunkten.  Wenn Sielink:link:reference-networking-saas-console-previous.html["vorherige Endpunkte"] , schlägt die Validierungsprüfung fehl.  Um diesen Fehler zu vermeiden, überspringen Sie die Validierungsprüfung.
+
Obwohl die vorherigen Endpunkte weiterhin unterstützt werden, empfiehlt NetApp , Ihre Firewall-Regeln so schnell wie möglich auf die aktuellen Endpunkte zu aktualisieren. link:reference-networking-saas-console-previous.html#update-endpoint-list["Erfahren Sie, wie Sie Ihre Endpunktliste aktualisieren"] .

* Wenn Sie auf die aktuellen Endpunkte in Ihrer Firewall aktualisieren, funktionieren Ihre vorhandenen Agenten weiterhin.


|===


== Vorbereiten des Netzwerks für den Konsolenagenten

Sie installieren den Konsolenagenten vor Ort oder in der Cloud und er kontaktiert Endpunkte, um von der Konsole initiierte Aktionen abzuschließen.

Konsolenagenten müssen Zugriff auf dieselben Endpunkte wie die NetApp Konsole haben, sowie auf zusätzliche Endpunkte, je nachdem, wo Sie den Agenten installieren.

Richten Sie den Netzwerk-Endpunktzugriff ein, bevor Sie den Konsolen-Agenten installieren.

* link:task-install-agent-aws-console.html#networking-aws-agent["Einrichten des AWS-Netzwerkzugriffs für einen Konsolenagenten"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Einrichten des Azure-Netzwerkzugriffs für einen Konsolen-Agent"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Einrichten des Google Cloud-Netzwerkzugriffs für einen Konsolenagenten"]
* link:task-install-agent-on-prem.html#network-access-agent["Einrichten des lokalen Netzwerkzugriffs für einen Konsolen-Agenten"]




== Vorbereiten des Netzwerks für Cloud Volumes ONTAP

Einige NetApp -Datendienste sowie Cloud Volumes ONTAP erfordern, dass der Agent über zusätzlichen ausgehenden Internetzugang verfügt.



=== Endpunkte für Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpunkte für Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Endpunkte für Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Endpunkte für Cloud Volumes ONTAP in Google Cloud"]


https://docs.netapp.com/us-en/data-services-family/["Weitere Informationen finden Sie in der entsprechenden Dokumentation zu NetApp Datendiensten."^]
