---
sidebar: sidebar 
permalink: reference-networking-saas-console-previous.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, netapp console 
summary: Sie müssen sicherstellen, dass die Konsole und alle von Ihnen installierten Agenten über den richtigen Netzwerkzugriff verfügen, um ordnungsgemäß zu funktionieren. 
---
= Netzwerkzugriff für frühere Versionen der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, der NetApp Console Agent und NetApp Datendienste erfordern ausgehenden Internetzugang, um die erforderlichen Endpunkte zu kontaktieren.


NOTE: In diesem Thema wird der Netzwerkzugriff dokumentiert, der für Versionen des NetApp Console Standardmodus 3.9.55 und darunter erforderlich ist.  Informationen zu den erforderlichen Endpunkten für 4.0.0 und höher finden Sie unterlink:reference-networking-saas-console.html["die erforderlichen Endpunkte für 4.0.0 und höher"] .

Sie müssen den Netzwerkzugriff für Folgendes einrichten:

* Computer, die als Software as a Service (SaaS) auf die NetApp Console zugreifen
* Konsolenagenten, die Sie vor Ort oder in der Cloud installieren.




[[update-your-endpoint-list-to-the-revised-list-for-4-0-0-and-higher]]
[[update-endpoint-list]]
== Aktualisieren Sie Ihre Endpunktliste auf die überarbeitete Liste für 4.0.0 und höher

Ab Version 4.0.0 benötigen Konsolenagenten weniger Endpunkte.  Vorhandene Bereitstellungen vor 4.0.0 werden weiterhin unterstützt.  Nach dem Upgrade auf 4.0.0 oder höher können Sie die alten Endpunkte bei Bedarf aus Ihrer Zulassungsliste entfernen.

NetApp empfiehlt, die Firewall-Regeln zu aktualisieren, um die überarbeitete Endpunktliste zu verwenden, die kleiner, sicherer und einfacher zu verwalten ist.  NetApp macht Platzhaltereinträge überflüssig und Endpunkte für Agent-Upgrades unterstützen alle Datendienste.

[cols="3*"]
|===
| *Endpunkte für Version 3.9.55 und älter* | *Endpunkte für 4.0.0 und höher* | *Zweck* 


 a| 
* \https://support.netapp.com
* \https://mysupport.netapp.com

 a| 
* \https://mysupport.netapp.com
* \https://signin.b2c.netapp.com
* \https://support.netapp.com

 a| 
Informationen zur Lizenzierung und Kontaktaufnahme mit dem NetApp -Support.



 a| 
* \https://*.api.bluexp.netapp.com
* \https://api.bluexp.netapp.com
* \https://*.cloudmanager.cloud.netapp.com
* \https://cloudmanager.cloud.netapp.com
* \https://netapp-cloud-account.auth0.com
* \https://netapp-cloud-account.us.auth0.com
* \https://console.netapp.com
* \https://*.console.netapp.com

 a| 
* \https://api.bluexp.netapp.com
* \https://netapp-cloud-account.auth0.com
* \https://netapp-cloud-account.us.auth0.com
* \https://console.netapp.com
* \https://components.console.bluexp.netapp.com
* \https://cdn.auth0.com

 a| 
Für den täglichen Betrieb.



 a| 
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io

 a| 
* \https://bluexpinfraprod.eastus2.data.azurecr.io
* \https://bluexpinfraprod.azurecr.io
* https://occmclientinfragov.azurecr.us.io (falls in einer eingeschränkten Modusumgebung)

| Um Bilder für Upgrades des Konsolenagenten zu erhalten. 
|===
.Schritte
. Stellen Sie sicher, dass Ihr Agent die Version 4.0.0 oder höher hat.link:task-troubleshoot-agent.html#view-the-console-agent-version["Agentenversion anzeigen."]
. Whitelist der Endpunkte inlink:reference-networking-saas-console.html["Unterstützte Endpunkte für 4.0.0 und höher"] .
. Starten Sie den Dienst „Service Manager 2“ auf jedem Agenten neu, indem Sie den folgenden Befehl ausführen:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Führen Sie den folgenden Befehl aus und überprüfen Sie, ob der Status des Agenten als _aktiv (wird ausgeführt)_ angezeigt wird: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----
. Entfernen Sie die alten Endpunkte aus der Zulassungsliste Ihrer Firewall.




[[endpoints-for-netapp-console-and-console-agents-for-3-9-55-and-below]]
== Endpunkte für NetApp Console und Konsolenagenten für 3.9.55 und darunter

Diese Endpunkte werden für Konsolenagenten 3.9.55 und darunter verwendet.

[cols="2*"]
|===
| Endpunkte | Zweck 


 a| 
\https://support.netapp.com \https://mysupport.netapp.com
 a| 
Um Lizenzinformationen zu erhalten und AutoSupport -Nachrichten an den NetApp Support zu senden.



 a| 
\https://\*.api.bluexp.netapp.com \https://api.bluexp.netapp.com \https://*.cloudmanager.cloud.netapp.com \https://cloudmanager.cloud.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com
| Um Funktionen und Dienste innerhalb der NetApp Console bereitzustellen. 


 a| 
Wählen Sie zwischen zwei Endpunktsätzen:

* Option 1 (empfohlen)
+
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io

* Option 2
+
\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io


 a| 
Um Bilder für Upgrades des Konsolenagenten zu erhalten.

NetApp empfiehlt, Endpunkte der Option 1 in Ihrer Firewall zuzulassen, da diese sicherer sind, und Endpunkte der Option 2 nicht zuzulassen, es sei denn, Sie verwenden Ransomware Resilience oder Backup and Recovery.  Beachten Sie Folgendes zu diesen Endpunkten:

* Option-1-Endpunkte werden ab Version 3.9.47 unterstützt. Versionen vor 3.9.47 unterstützen keine Abwärtskompatibilität.
* Der Konsolenagent kontaktiert zuerst die Endpunkte in Option 2. Wenn diese Endpunkte nicht erreichbar sind, kontaktiert er automatisch die Endpunkte in Option 1.
* Wenn Sie den Konsolenagenten mit NetApp Backup and Recovery oder Ransomware Resilience verwenden, unterstützt das System keine Endpunkte der Option 1.  Erlauben Sie Endpunkte der Option 2 und verbieten Sie Option 1.


|===


[[cloud-provider-endpoints-contacted-by-the-console-agent]]
== Vom Konsolenagenten kontaktierte Cloud-Provider-Endpunkte

Konsolenagenten müssen Zugriff auf zusätzliche Endpunkte haben, wenn diese bei Ihrem Cloud-Anbieter bereitgestellt werden.

Aktivieren Sie den Zugriff auf die Endpunkte des Cloud-Anbieters, bevor Sie den Konsolenagenten installieren.

* link:task-install-agent-aws-console.html#networking-aws-agent["Einrichten des AWS-Netzwerkzugriffs für einen Konsolenagenten"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Einrichten des Azure-Netzwerkzugriffs für einen Konsolen-Agent"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Einrichten des Google Cloud-Netzwerkzugriffs für einen Konsolenagenten"]


Die Endpunkte des Cloud-Anbieters sind für alle Versionen gleich.



[[data-services-endpoints-contacted-by-the-console-agent]]
== Vom Konsolenagenten kontaktierte Datendienstendpunkte

Der Konsolenagent erfordert zusätzlichen ausgehenden Internetzugang, um einige NetApp Datendienste und Cloud Volumes ONTAP zu unterstützen.



[[endpoints-for-cloud-volumes-ontap]]
=== Endpunkte für Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpunkte für Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Endpunkte für Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Endpunkte für Cloud Volumes ONTAP in Google Cloud"]

