---
sidebar: sidebar 
permalink: reference-whats-next.html 
keywords: standard mode, what you can do 
summary: Nachdem Sie sich angemeldet und die NetApp Konsole im Standardmodus eingerichtet haben, können Benutzer Speichersysteme erstellen und erkennen sowie NetApp -Datendienste verwenden. 
---
= Was Sie als Nächstes tun können (Standardmodus)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie sich angemeldet und die NetApp Konsole im Standardmodus eingerichtet haben, können Benutzer Speichersysteme erstellen und erkennen sowie NetApp -Datendienste verwenden.


TIP: Wenn Sie einen Konsolenagenten in AWS, Microsoft Azure oder Google Cloud installiert haben, erkennt die Konsole automatisch Informationen zu den Amazon S3-Buckets, Azure Blob Storage oder Google Cloud Storage-Buckets am Standort, an dem der Agent installiert ist.  Diese Systeme werden automatisch zur Seite *Systeme* hinzugefügt.

Hilfe erhalten Sie unter https://docs.netapp.com/us-en/bluexp-family/["Homepage für die NetApp Console-Dokumentation"^] um die Dokumentation zur NetApp -Konsole anzuzeigen.

.Ähnliche Informationen
link:concept-modes.html["Bereitstellungsmodi der NetApp Konsole"]
