---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: NetApp Console, der NetApp Console Agent und NetApp Datendienste erfordern ausgehenden Internetzugang und die Möglichkeit, die erforderlichen Endpunkte zu kontaktieren. 
---
= Netzwerkzugriff für die NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console, der NetApp Console Agent und NetApp Datendienste erfordern ausgehenden Internetzugang und die Möglichkeit, die erforderlichen Endpunkte zu kontaktieren.

Sie müssen den Netzwerkzugriff für Folgendes einrichten:

* Computer, die als Software as a Service (SaaS) auf die NetApp Console zugreifen
* Konsolenagenten, die Sie vor Ort oder in der Cloud installieren. Konsolenagenten.



NOTE: Mit 4.0.0 hat NetApp die erforderlichen Netzwerkendpunkte für die Konsole und Konsolenagenten reduziert, wodurch die Sicherheit verbessert und die Bereitstellung vereinfacht wird. Wichtig ist, dass alle Bereitstellungen vor Version 4.0.0 weiterhin vollständig unterstützt werden.  Während vorherige Endpunkte für vorhandene Agenten weiterhin verfügbar bleiben, empfiehlt NetApp dringend, die Firewall-Regeln auf die aktuellen Endpunkte zu aktualisieren, nachdem die erfolgreichen Agent-Upgrades bestätigt wurden.link:reference-networking-saas-console-previous.html["Erfahren Sie, wie Sie Ihre Endpunktliste aktualisieren."]



[[endpoints-contacted-by-netapp-console-and-console-agents]]
== Von der NetApp Console und den Konsolenagenten kontaktierte Endpunkte

Jeder von Ihnen bereitgestellte Agent und jeder Computer, der auf die NetApp Console zugreift, muss über Verbindungen zu den unten aufgeführten Endpunkten verfügen.

Konsolenagenten, die bei Ihrem Cloud-Anbieter bereitgestellt werden, benötigen Zugriff auf die jeweiligen Endpunkte dieses Cloud-Anbieters.

[cols="2*"]
|===
| Endpunkte | Zweck 


| \https://mysupport.netapp.com | Um Lizenzinformationen zu erhalten und AutoSupport-Nachrichten an NetApp Support zu senden. 


| \https://signin.b2c.netapp.com | So aktualisieren Sie die Anmeldeinformationen der NetApp Support Site (NSS) oder fügen der NetApp Console neue NSS-Anmeldeinformationen hinzu. 


| \https://support.netapp.com | Um Lizenzinformationen zu erhalten und AutoSupport-Nachrichten an NetApp Support zu senden sowie Software-Updates für Cloud Volumes ONTAP zu erhalten. 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com | Um Funktionen und Dienste innerhalb der NetApp Console bereitzustellen. 


 a| 
https://bluexpinfraprod.eastus2.data.azurecr.io https://bluexpinfraprod.azurecr.io https://occmclientinfragov.azurecr.us (wird für Bereitstellungen im eingeschränkten Modus benötigt)
 a| 
Um Bilder für Upgrades des Konsolenagenten zu erhalten.

|===


[[cloud-provider-endpoints-contacted-the-console-agent]]
== Cloud-Provider-Endpunkte haben den Konsolen-Agenten kontaktiert

Konsolenagenten müssen Zugriff auf zusätzliche Endpunkte haben, wenn diese bei Ihrem Cloud-Anbieter bereitgestellt werden.

Richten Sie den Netzwerk-Endpunktzugriff des Cloud-Anbieters ein, bevor Sie den Konsolen-Agenten installieren.

* link:task-install-agent-aws-console.html#networking-aws-agent["Einrichten des AWS-Netzwerkzugriffs für einen Konsolenagenten"]
* link:task-install-agent-azure-console.html#networking-azure-agent["Einrichten des Azure-Netzwerkzugriffs für einen Konsolen-Agent"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["Einrichten des Google Cloud-Netzwerkzugriffs für einen Konsolenagenten"]




[[data-services-endpoints-contacted-by-the-console-agent]]
== Vom Konsolenagenten kontaktierte Datendienstendpunkte

Einige NetApp -Datendienste sowie Cloud Volumes ONTAP erfordern, dass der Agent über zusätzlichen ausgehenden Internetzugang verfügt.



[[endpoints-for-cloud-volumes-ontap]]
=== Endpunkte für Cloud Volumes ONTAP

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["Endpunkte für Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Endpunkte für Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Endpunkte für Cloud Volumes ONTAP in Google Cloud"]




[[endpoints-for-workloads]]
=== Endpunkte für Workloads

Der Console-Agent muss für NetApp -Workloads auf den folgenden Endpunkt zugreifen können.

[cols="2*"]
|===
| Endpunkte | Zweck 


 a| 
\https://api.workloads.netapp.com
 a| 
Die webbasierte Konsole kontaktiert diesen Endpunkt, um mit den Workload Factory APIs zu interagieren und FSx for ONTAP-basierte Workloads zu verwalten und zu betreiben.



 a| 
\https://ws.workloads.bluexp.netapp.com
 a| 
Wird vom Workload Factory Backend verwendet, um den Console Agenten nach ONTAP-Operationen abzufragen.

|===