---
sidebar: sidebar 
permalink: reference-permissions-gcp.html 
keywords: permissions, gcp, gcp permissions, bluexp, console agent 
summary: Der Konsolenagent benötigt Berechtigungen, um Aktionen bei Ihrem Cloud-Anbieter auszuführen.  Diese Berechtigungen sind in den von NetApp bereitgestellten Richtlinien enthalten.  Sie sollten verstehen, was der Agent mit diesen Berechtigungen macht. 
---
= Google Cloud-Berechtigungen für den NetApp Console-Agenten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der Konsolenagent benötigt Berechtigungen zum Ausführen von Aktionen in Google Cloud. Diese Berechtigungen sind in einer benutzerdefinierten Rolle enthalten, die von NetApp bereitgestellt wird. Sie sollten verstehen, was der Agent mit diesen Berechtigungen macht.



== Berechtigungen für Google Cloud-Nutzerkonten

Die unten stehende benutzerdefinierte Rolle gewährt einem Google Cloud-Benutzer die erforderlichen Berechtigungen zum Bereitstellen eines Agenten.  Weisen Sie diese benutzerdefinierte Rolle dem Benutzer zu, der den Agenten bereitstellen wird.

.Google Cloud-Nutzerkontoberechtigungen anzeigen
[%collapsible]
====
[source, yaml]
----
title: Console agent deployment policy
description: Permissions for the user who deploys the Console agent
stage: GA
includedPermissions:

- cloudbuild.builds.get
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- config.deployments.create
- config.operations.get
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getState
- config.deployments.list
- config.deployments.update
- config.deployments.updateState
- config.previews.get
- config.previews.list
- config.revisions.get
- config.resources.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.create
- storage.buckets.get
- storage.objects.create
- storage.folders.create
- storage.objects.list

----
====


== Dienstkontoberechtigungen

Die unten stehende benutzerdefinierte Rolle weist dem mit dem Console-Agenten verknüpften Google Cloud-Dienstkonto die Berechtigungen zu, die zum Verwalten von Ressourcen und Prozessen in Ihrem Google Cloud-Netzwerk erforderlich sind.

Weisen Sie diese benutzerdefinierte Rolle einem Dienstkonto zu, das mit der Console-Agent-VM verbunden ist.

* link:task-install-agent-google-console-gcloud.html#agent-permissions-google["Google Cloud-Berechtigungen für den Standardmodus einrichten"]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Berechtigungen für den eingeschränkten Modus einrichten"]


.Google-Dienstkontoberechtigungen anzeigen
[%collapsible]
====
Stellen Sie sicher, dass die Rolle auf dem neuesten Stand ist, da in nachfolgenden Versionen neue Berechtigungen hinzugefügt oder entfernt werden.  Im Änderungsprotokoll sind alle erforderlichen neuen Berechtigungen aufgeführt.link:reference-permissions-gcp.html#gcp-permissions-change-log["Überprüfen Sie das Änderungsprotokoll der Google-Berechtigungen."] link:task-adding-gcp-accounts.html["Lesen Sie, wie Sie Google Cloud-Dienstkonten hinzufügen."]

[source, yaml]
----
title: NetApp Console agent
description: Permissions for the service account associated with the Console agent.
stage: GA
includedPermissions:
- cloudbuild.builds.get
- cloudbuild.connections.list
- cloudbuild.repositories.accessReadToken
- cloudbuild.repositories.list
- cloudbuild.workerpools.list
- cloudbuild.workerpools.get
- cloudquotas.quotas.get
- cloudkms.cryptoKeys.getIamPolicy
- cloudkms.cryptoKeys.setIamPolicy
- cloudkms.keyRings.get
- cloudkms.keyRings.getIamPolicy
- cloudkms.keyRings.setIamPolicy
- config.artifacts.import
- config.deployments.create
- config.deployments.delete
- config.deployments.deleteState
- config.deployments.get
- config.deployments.getLock
- config.deployments.getState
- config.deployments.list
- config.deployments.lock
- config.deployments.update
- config.deployments.updateState
- config.previews.upload
- config.revisions.get
- config.revisions.getState
- config.operations.get
- config.previews.get
- config.previews.list
- config.resources.list
- compute.regionBackendServices.create
- compute.regionBackendServices.get
- compute.regionBackendServices.list
- compute.regionBackendServices.update
- compute.networks.updatePolicy
- compute.addresses.createInternal
- compute.addresses.deleteInternal
- compute.addresses.list
- compute.addresses.setLabels
- compute.addresses.useInternal
- compute.backendServices.create
- compute.disks.create
- compute.disks.createSnapshot
- compute.disks.delete
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.update
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.forwardingRules.create
- compute.forwardingRules.delete
- compute.forwardingRules.get
- compute.forwardingRules.setLabels
- compute.forwardingRules.update
- compute.globalOperations.get
- compute.healthChecks.create
- compute.healthChecks.delete
- compute.healthChecks.get
- compute.healthChecks.useReadOnly
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.addAccessConfig
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.delete
- compute.instances.detachDisk
- compute.instances.get
- compute.instances.getSerialPortOutput
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.stop
- compute.instances.updateDisplayDevice
- compute.instances.use
- compute.instanceGroups.create
- compute.instanceGroups.delete
- compute.instanceGroups.get
- compute.instanceGroups.update
- compute.instanceGroups.use
- compute.addresses.get
- compute.instances.updateNetworkInterface
- compute.instances.setMinCpuPlatform
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.regionBackendServices.delete
- compute.regionBackendServices.use
- compute.resourcePolicies.create
- compute.resourcePolicies.delete
- compute.resourcePolicies.get
- compute.snapshots.create
- compute.snapshots.delete
- compute.snapshots.get
- compute.snapshots.list
- compute.snapshots.setLabels
- compute.subnetworks.get
- compute.subnetworks.list
- compute.subnetworks.use
- compute.subnetworks.useExternalIp
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- compute.instances.setServiceAccount
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- logging.logEntries.list
- logging.privateLogEntries.list
- logging.logEntries.create
- logging.logEntries.route
- monitoring.timeSeries.list
- resourcemanager.projects.get
- storage.buckets.create
- storage.buckets.delete
- storage.buckets.get
- storage.buckets.list
- storage.objects.create
- storage.objects.delete
- storage.objects.get
- storage.objects.list
- storage.objects.update
- cloudkms.cryptoKeyVersions.useToEncrypt
- cloudkms.cryptoKeys.get
- cloudkms.cryptoKeys.list
- cloudkms.keyRings.list
- storage.buckets.update
- iam.serviceAccounts.actAs
- iam.serviceAccounts.create
- iam.serviceAccounts.get
- iam.serviceAccounts.getIamPolicy
- iam.serviceAccounts.list
- iam.serviceAccountKeys.create
- storage.buckets.getIamPolicy



----
====


== So werden Google Cloud-Berechtigungen verwendet

Der Console-Agent nutzt die Berechtigungen in der benutzerdefinierten Rolle, um Cloud Volumes ONTAP Ressourcen und NetApp -Datendienstprozesse in Ihrem Google Cloud-Netzwerk zu verwalten.  In den folgenden Abschnitten wird beschrieben, wie der Agent diese Berechtigungen nutzt.



=== Für Cloud Volumes ONTAP verwendete Berechtigungen

Der Console-Agent nutzt die Berechtigungen in der benutzerdefinierten Rolle, um Cloud Volumes ONTAP Ressourcen und -Prozesse in Ihrem Google Cloud-Netzwerk zu verwalten.  In den folgenden Abschnitten wird beschrieben, wie der Agent diese Berechtigungen nutzt.

.Berechtigungen für Cloud Volumes ONTAP
[%collapsible]
====
[cols="5*"]
|===
| Aktionen | Zweck | Wird für die Bereitstellung verwendet? | Wird es für den täglichen Betrieb verwendet? | Zum Löschen verwendet? 


| config.deployments.create .15+| Um die virtuelle Maschineninstanz Cloud Volumes ONTAP mithilfe von Google Cloud Infrastructure Manager bereitzustellen. | Ja | Nein | Nein 


| config.deployments.delete | Nein | Nein | Ja 


| config.deployments.deleteState | Nein | Nein | Ja 


| config.deployments.get | Nein | Ja | Ja 


| config.deployments.getLock | Nein | Ja | Nein 


| config.deployments.getState | Nein | Ja | Nein 


| config.deployments.list | Nein | Ja | Nein 


| config.deployments.lock | Nein | Ja | Nein 


| config.deployments.update | Nein | Ja | Nein 


| config.deployments.updateState | Nein | Ja | Nein 


| config.operations.get | Nein | Ja | Nein 


| config.previews.get | Nein | Ja | Nein 


| config.previews.list | Nein | Ja | Nein 


| config.resources.list | Nein | Ja | Nein 


| config.revisions.get | Nein | Ja | Nein 


| compute.disks.create .8+| Zum Erstellen und Verwalten von Datenträgern auf Cloud Volumes ONTAP-Systemen. | Ja | Ja | Nein 


| compute.disks.createSnapshot | Nein | Ja | Nein 


| compute.disks.delete | Nein | Ja | Ja 


| compute.disks.get | Nein | Ja | Nein 


| compute.disks.list | Ja | Ja | Nein 


| compute.disks.setLabels | Ja | Ja | Nein 


| compute.disks.update | Nein | Ja | Nein 


| compute.disks.use | Nein | Ja | Nein 


| compute.firewalls.create .4+| So erstellen Sie Firewall-Regeln für Cloud Volumes ONTAP. | Ja | Nein | Nein 


| compute.firewalls.delete | Nein | Ja | Ja 


| compute.firewalls.get | Ja | Ja | Nein 


| compute.firewalls.list | Ja | Ja | Nein 


| compute.forwardingRules.create | Erstellen Sie Weiterleitungsregeln für das Routing des Datenverkehrs zu Backend-Diensten. | Nein | Ja | Nein 


| compute.forwardingRules.delete | Vorhandene Weiterleitungsregeln löschen. | Nein | Ja | Nein 


| compute.forwardingRules.get | Details zu bestehenden Weiterleitungsregeln abrufen. | Nein | Ja | Nein 


| compute.forwardingRules.setLabels | Labels für Weiterleitungsregeln der Organisation festlegen oder aktualisieren. | Nein | Ja | Nein 


| compute.forwardingRules.update | Aktualisieren Sie bestehende Weiterleitungsregeln für das Verkehrsmanagement. | Nein | Ja | Nein 


| compute.globalOperations.get | Um den Status von Vorgängen abzurufen. | Ja | Ja | Nein 


| compute.healthChecks.create .4+| Erstellung und Verwaltung von Gesundheitsprüfungen zur Überwachung des Zustands der Backend-Dienste. | Nein | Ja | Nein 


| compute.healthChecks.delete | Nein | Ja | Nein 


| compute.healthChecks.get | Nein | Ja | Nein 


| compute.healthChecks.useReadOnly | Nein | Ja | Nein 


| compute.images.get .4+| Um Bilder für VM-Instanzen zu erhalten. | Ja | Nein | Nein 


| compute.images.getFromFamily | Ja | Nein | Nein 


| compute.images.list | Ja | Nein | Nein 


| compute.images.useReadOnly | Ja | Nein | Nein 


| compute.instances.attachDisk .2+| So schließen Sie Festplatten an Cloud Volumes ONTAP an und trennen sie davon. | Ja | Ja | Nein 


| compute.instances.detachDisk | Nein | Ja | Ja 


| compute.instances.create .2+| Zum Erstellen und Löschen von Cloud Volumes ONTAP VM-Instanzen. | Ja | Nein | Nein 


| compute.instances.delete | Nein | Nein | Ja 


| compute.instances.get | Zum Auflisten von VM-Instanzen. | Ja | Ja | Nein 


| compute.instances.getSerialPortOutput | Um Konsolenprotokolle zu erhalten. | Ja | Ja | Nein 


| compute.instances.list | Zum Abrufen der Liste der Instanzen in einer Zone. | Ja | Ja | Nein 


| compute.instances.setDeletionProtection | Um den Löschschutz für die Instanz festzulegen. | Ja | Nein | Nein 


| compute.instances.setLabels | Um Beschriftungen hinzuzufügen. | Ja | Nein | Nein 


| compute.instances.setMachineType .2+| So ändern Sie den Maschinentyp für Cloud Volumes ONTAP. | Ja | Ja | Nein 


| compute.instances.setMinCpuPlatform | Ja | Ja | Nein 


| compute.instances.setMetadata | Um Metadaten hinzuzufügen. | Ja | Ja | Nein 


| compute.instances.setTags | So fügen Sie Tags für Firewall-Regeln hinzu. | Ja | Ja | Nein 


| compute.instances.start .3+| So starten und stoppen Sie Cloud Volumes ONTAP. | Ja | Ja | Nein 


| compute.instances.stop | Ja | Ja | Nein 


| compute.instances.updateDisplayDevice | Ja | Ja | Nein 


| compute.instances.use | Nutzen Sie virtuelle Maschineninstanzen (Start-, Stopp- und Verbindungsvorgänge). | Nein | Ja | Nein 


| compute.machineTypes.get | Um die Anzahl der Kerne zu ermitteln und die Quoten zu überprüfen. | Ja | Nein | Nein 


| compute.projects.get | Zur Unterstützung mehrerer Projekte. | Ja | Nein | Nein 


| compute.resourcePolicies.create .3+| Ressourcenrichtlinien für die automatisierte Ressourcenverwaltung erstellen und verwalten. | Nein | Ja | Nein 


| compute.resourcePolicies.delete | Nein | Ja | Nein 


| compute.resourcePolicies.get | Nein | Ja | Nein 


| compute.snapshots.create .5+| Zum Erstellen und Verwalten persistenter Festplatten-Snapshots. | Ja | Ja | Nein 


| compute.snapshots.delete | Nein | Ja | Ja 


| compute.snapshots.get | Nein | Ja | Nein 


| compute.snapshots.list | Nein | Ja | Nein 


| compute.snapshots.setLabels | Ja | Ja | Nein 


| compute.networks.get .9+| Um die Netzwerkinformationen zu erhalten, die zum Erstellen einer neuen Cloud Volumes ONTAP VM-Instanz erforderlich sind. | Ja | Ja | Nein 


| compute.networks.list | Ja | Ja | Nein 


| compute.regions.get | Ja | Ja | Nein 


| compute.regions.list | Ja | Ja | Nein 


| compute.subnetworks.get | Ja | Ja | Nein 


| compute.subnetworks.list | Ja | Ja | Nein 


| compute.zoneOperations.get | Ja | Ja | Nein 


| compute.zones.get | Ja | Ja | Nein 


| compute.zones.list | Ja | Ja | Nein 


| deploymentmanager.compositeTypes.get .16+| So stellen Sie die Cloud Volumes ONTAP VM-Instanz mithilfe von Google Cloud Deployment Manager bereit. | Ja | Nein | Nein 


| deploymentmanager.compositeTypes.list | Ja | Nein | Nein 


| deploymentmanager.deployments.create | Ja | Nein | Nein 


| deploymentmanager.deployments.delete | Ja | Nein | Nein 


| deploymentmanager.deployments.get | Ja | Nein | Nein 


| deploymentmanager.deployments.list | Ja | Nein | Nein 


| deploymentmanager.manifests.get | Ja | Nein | Nein 


| deploymentmanager.manifests.list | Ja | Nein | Nein 


| deploymentmanager.operations.get | Ja | Nein | Nein 


| deploymentmanager.operations.list | Ja | Nein | Nein 


| deploymentmanager.resources.get | Ja | Nein | Nein 


| deploymentmanager.resources.list | Ja | Nein | Nein 


| deploymentmanager.typeProviders.get | Ja | Nein | Nein 


| deploymentmanager.typeProviders.list | Ja | Nein | Nein 


| deploymentmanager.types.get | Ja | Nein | Nein 


| deploymentmanager.types.list | Ja | Nein | Nein 


| logging.logEntries.list .2+| Um Stack-Log-Laufwerke zu erhalten. | Ja | Ja | Nein 


| logging.privateLogEntries.list | Ja | Ja | Nein 


| logging.logEntries.create .2+| Protokolleinträge erstellen und weiterleiten für Überwachung, Fehlersuche und Prüfung. | Ja | Ja | Nein 


| logging.logEntries.route | Ja | Ja | Nein 


| resourcemanager.projects.get | Zur Unterstützung mehrerer Projekte. | Ja | Ja | Nein 


| storage.buckets.create .5+| So erstellen und verwalten Sie einen Google Cloud Storage-Bucket für die Datenschichtung. | Ja | Ja | Nein 


| storage.buckets.delete | Nein | Ja | Ja 


| storage.buckets.get | Nein | Ja | Nein 


| storage.buckets.list | Nein | Ja | Nein 


| storage.buckets.update | Nein | Ja | Nein 


| cloudkms.cryptoKeyVersions.useToEncrypt .5+| So verwenden Sie vom Kunden verwaltete Verschlüsselungsschlüssel vom Cloud Key Management Service mit Cloud Volumes ONTAP. | Ja | Ja | Nein 


| cloudkms.cryptoKeys.get | Ja | Ja | Nein 


| cloudkms.cryptoKeys.list | Ja | Ja | Nein 


| cloudkms.keyRings.list | Ja | Ja | Nein 


| cloudbuild.builds.get | Ja | Nein | Nein 


| cloudbuild.workerpools.get | Zugriff auf Worker-Pool-Informationen während der Bereitstellung im privaten Modus und der Konvertierung von Cloud Volumes ONTAP-Systemen mithilfe von Infrastructure Manager. | Ja | Ja | Ja 


| cloudbuild.workerpools.list | Informationen zum Worker-Pool während der Bereitstellung von Cloud Volumes ONTAP-Systemen im privaten Modus mithilfe von Infrastructure Manager auflisten. | Ja | Nein | Nein 


| compute.instances.setServiceAccount .6+| So richten Sie ein Dienstkonto auf der Cloud Volumes ONTAP -Instanz ein.  Dieses Dienstkonto bietet Berechtigungen für die Datenschichtung in einem Google Cloud Storage-Bucket. | Ja | Ja | Nein 


| iam.serviceAccounts.actAs | Ja | Nein | Nein 


| iam.serviceAccounts.create | Ja | Nein | Nein 


| iam.serviceAccounts.getIamPolicy | Ja | Ja | Nein 


| iam.serviceAccounts.list | Ja | Ja | Nein 


| iam.serviceAccountKeys.create | Ja | Nein | Nein 


| storage.objects.create .4+| Objekte (Dateien) im Google Cloud Storage-Bucket erstellen und verwalten. | Ja | Ja | Nein 


| storage.objects.delete | Nein | Nein | Ja 


| storage.objects.get | Ja | Ja | Nein 


| storage.objects.list | Ja | Ja | Nein 


| compute.addresses.list | Zum Abrufen der Adressen in einer Region beim Bereitstellen eines HA-Paares. | Ja | Nein | Nein 


| compute.addresses.createInternal | Erstellen Sie interne IP-Adressen innerhalb des VPC-Netzwerks zur Ressourcenzuweisung. | Nein | Ja | Nein 


| compute.addresses.deleteInternal | Interne IP-Adressen zur Ressourcenbereinigung löschen. | Nein | Ja | Nein 


| compute.addresses.setLabels | Aktualisieren Sie die Bezeichnungen der Adressressource. | Nein | Ja | Nein 


| compute.addresses.useInternal | Für die Netzwerkkommunikation interne IP-Adressen verwenden. | Nein | Ja | Nein 


| compute.backendServices.create | So konfigurieren Sie einen Backend-Dienst zum Verteilen des Datenverkehrs in einem HA-Paar. | Ja | Nein | Nein 


| compute.regionBackendServices.create .6+| Backend-Dienste für das Traffic-Routing erstellen und verwalten. | Ja | Nein | Nein 


| compute.regionBackendServices.delete | Nein | Ja | Nein 


| compute.regionBackendServices.get | Ja | Nein | Nein 


| compute.regionBackendServices.update | Ja | Ja | Nein 


| compute.regionBackendServices.list | Ja | Nein | Nein 


| compute.regionBackendServices.use | Nein | Ja | Nein 


| compute.networks.updatePolicy | So wenden Sie Firewall-Regeln auf die VPCs und Subnetze für ein HA-Paar an. | Ja | Nein | Nein 


| compute.instanceGroups.get .7+| Zum Erstellen und Verwalten von Speicher-VMs auf Cloud Volumes ONTAP HA-Paaren. | Ja | Ja | Nein 


| compute.addresses.get | Ja | Ja | Nein 


| compute.instances.updateNetworkInterface | Ja | Ja | Nein 


| compute.instanceGroups.create | Nein | Ja | Nein 


| compute.instanceGroups.delete | Nein | Ja | Nein 


| compute.instanceGroups.update | Nein | Ja | Nein 


| compute.instanceGroups.use | Nein | Ja | Nein 


| monitoring.timeSerieslist .2+| Um Informationen zu Google Cloud Storage-Buckets zu erhalten. | Ja | Ja | Nein 


| storage.buckets.getIamPolicy | Ja | Ja | Nein 
|===
====


=== Für NetApp Backup and Recovery verwendete Berechtigungen

Der Console-Agent nutzt die Berechtigungen in der benutzerdefinierten Rolle, um NetApp Backup and Recovery Ressourcen und -Prozesse in Ihrem Google Cloud-Netzwerk zu verwalten.  In den folgenden Abschnitten wird beschrieben, wie der Agent diese Berechtigungen nutzt.

.Berechtigungen für NetApp Backup and Recovery anzeigen
[%collapsible]
====
[cols="5*"]
|===


| Aktionen | Zweck | Wird für die Bereitstellung verwendet? | Wird es für den täglichen Betrieb verwendet? | Zum Löschen verwendet? 


 a| 
* cloudkms.cryptoKeys.get
* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.list
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.list
* cloudkms.keyRings.setIamPolicy

| So wählen Sie im Aktivierungsassistenten von NetApp Backup and Recovery Ihre eigenen, vom Kunden verwalteten Schlüssel aus, anstatt die standardmäßigen, von Google verwalteten Verschlüsselungsschlüssel zu verwenden. | Ja | Ja | Nein 
|===
====


=== Für die NetApp Data Classification verwendete Berechtigungen

Der Console-Agent nutzt die Berechtigungen in der benutzerdefinierten Rolle, um NetApp Data Classification Ressourcen und -Prozesse in Ihrem Google Cloud-Netzwerk zu verwalten.  In den folgenden Abschnitten wird beschrieben, wie der Agent diese Berechtigungen nutzt.

.Berechtigungen für die NetApp Data Classification anzeigen
[%collapsible]
====
[cols="5*"]
|===


| Aktionen | Zweck | Wird für die Bereitstellung verwendet? | Wird es für den täglichen Betrieb verwendet? | Zum Löschen verwendet? 


 a| 
* compute.subnetworks.use
* compute.subnetworks.useExternalIp
* compute.instances.addAccessConfig

| So aktivieren Sie die NetApp Data Classification. | Ja | Nein | Nein 
|===
====


== Änderungsprotokoll

Die hinzugefügten und entfernten Berechtigungen sind unten aufgeführt.



=== 13. April 2026

Die  `compute.disks.update`Berechtigung wird hinzugefügt, um IOPS- und Durchsatzparameter auf einem Hyperdisk Balanced-Aggregat oder einer Festplatte in Cloud Volumes ONTAP Systemen zu aktualisieren.



=== 26. Februar 2026

Die  `cloudbuild.workerpools.get` und  `cloudbuild.workerpools.list` Berechtigungen wurden hinzugefügt, um Infrastructure Manager bei privaten Bereitstellungen von Cloud Volumes ONTAP in Google Cloud zu unterstützen.



=== 09. Februar 2026

Die  `compute.forwardingRules.update`Berechtigung wurde hinzugefügt, um Infrastructure Manager in Cloud Volumes ONTAP-Bereitstellungen in Google Cloud zu unterstützen.



=== 8. Dezember 2025

NetApp wechselt von Google Cloud Deployment Manager zu Google Cloud Infrastructure Manager (IM), um den Console-Agenten in Google Cloud bereitzustellen und auszuführen.  Um diese Änderung zu unterstützen, wurden die folgenden Berechtigungen hinzugefügt.

Für den Google Cloud-Nutzer, der den Agenten bereitstellt, sind folgende zusätzliche Berechtigungen erforderlich:

* storage.buckets.create
* storage.buckets.get
* storage.objects.create
* storage.folders.create
* storage.objects.list
* iam.serviceAccount.actAs
* config.deployments.create
* config.operations.get


Für das Dienstkonto in Google Cloud, das für den täglichen Betrieb verwendet wird, sind folgende zusätzliche Berechtigungen erforderlich:

* cloudbuild.connections.list
* cloudbuild.repositories.accessReadToken
* cloudbuild.repositories.list
* cloudquotas.quotas.get
* config.artifacts.import
* config.deployments.deleteState
* config.deployments.getLock
* config.deployments.getState
* config.deployments.updateState
* config.previews.upload
* config.revisions.getState
* logging.logEntries.create
* storage.objects.create
* storage.objects.delete
* storage.objects.update
* iam.serviceAccounts.get


Für die Bereitstellung von Cloud Volumes ONTAP sind folgende zusätzliche Berechtigungen erforderlich:

* cloudbuild.builds.get
* config.deployments.delete
* config.deployments.deleteState
* config.deployments.get
* config.deployments.getState
* config.deployments.list
* config.deployments.update
* config.deployments.updateState
* config.previews.get
* config.previews.list
* config.revisions.get
* config.resources.list
* iam.serviceAccountKeys.create
* iam.serviceAccounts.create


Für das Dienstkonto, das für den täglichen Betrieb von Cloud Volumes ONTAP verwendet wird, sind die folgenden zusätzlichen Berechtigungen erforderlich.

* compute.addresses.createInternal
* compute.addresses.deleteInternal
* compute.addresses.setLabels
* compute.addresses.useInternal
* compute.forwardingRules.create
* compute.forwardingRules.delete
* compute.forwardingRules.get
* compute.forwardingRules.setLabels
* compute.healthChecks.create
* compute.healthChecks.delete
* compute.healthChecks.get
* compute.healthChecks.useReadOnly
* compute.instanceGroups.create
* compute.instanceGroups.delete
* compute.instanceGroups.update
* compute.instanceGroups.use
* compute.instances.use
* compute.regionBackendServices.delete
* compute.regionBackendServices.update
* compute.regionBackendServices.use
* compute.resourcePolicies.create
* compute.resourcePolicies.delete
* compute.resourcePolicies.get
* logging.logEntries.route
* config.deployments.create
* config.deployments.delete
* config.deployments.get
* config.deployments.update
* config.revisions.get
* config.deployments.lock
* config.operations.get




=== 26. November 2025

Die Berechtigungen wurden aktualisiert, um ihre Verwendung klarer zu gestalten; es wurden jedoch keine Berechtigungen hinzugefügt oder entfernt. Es wurden drei Spalten hinzugefügt, um anzuzeigen, ob die jeweilige Berechtigung für die Bereitstellung, den täglichen Betrieb oder die Löschung verwendet wird. Darüber hinaus sind einige Berechtigungen nach ihrer Verwendung für NetApp Data Classification und NetApp Backup and Recovery getrennt.



=== 06. Februar 2023

Die folgende Berechtigung wurde dieser Richtlinie hinzugefügt:

* compute.instances.updateNetworkInterface


Diese Berechtigung ist für Cloud Volumes ONTAP erforderlich.



=== 27.01.2023

Folgende Berechtigungen wurden dieser Richtlinie hinzugefügt:

* cloudkms.cryptoKeys.getIamPolicy
* cloudkms.cryptoKeys.setIamPolicy
* cloudkms.keyRings.get
* cloudkms.keyRings.getIamPolicy
* cloudkms.keyRings.setIamPolicy


Diese Berechtigungen sind für NetApp Backup and Recovery erforderlich.
