---
sidebar: sidebar 
permalink: reference-ports-azure.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: Die Azure-Sicherheitsgruppe für den Agenten erfordert sowohl eingehende als auch ausgehende Regeln. Die NetApp Console erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Console-Agenten über die Console erstellen. Bei anderen Installationsoptionen müssen Sie diese Sicherheitsgruppe manuell einrichten. 
---
= Sicherheitsgruppenregeln für Konsolen-Agents in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die Azure-Sicherheitsgruppe für den Agenten erfordert sowohl eingehende als auch ausgehende Regeln. Die NetApp Console erstellt diese Sicherheitsgruppe automatisch, wenn Sie einen Console-Agenten über die Console erstellen. Bei anderen Installationsoptionen müssen Sie diese Sicherheitsgruppe manuell einrichten.



[[inbound-rules]]
== Eingehende Regeln

[cols="3*"]
|===
| Protokoll | Hafen | Zweck 


| SSH | 22 | Bietet SSH-Zugriff auf den Agent-Host 


| HTTP | 80  a| 
* Bietet HTTP-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche
* Wird während des Upgrade-Prozesses von Cloud Volumes ONTAP verwendet




| HTTPS | 443 | Bietet HTTPS-Zugriff von Client-Webbrowsern auf die lokale Benutzeroberfläche und Verbindungen von der NetApp Data Classification -Instanz 


| TCP | 3128 | Bietet Cloud Volumes ONTAP Internetzugang, um AutoSupport Nachrichten an den NetApp Support zu senden.  Sie müssen diesen Port nach der Bereitstellung manuell öffnen. https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-verify-autosupport.html["Erfahren Sie, wie der Agent als Proxy für AutoSupport -Nachrichten verwendet wird"^] 
|===


[[outbound-rules]]
== Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für den Agenten öffnet den gesamten ausgehenden Datenverkehr.  Wenn das akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Nachrichten.  Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Ausgangsregeln.



[[basic-outbound-rules]]
=== Grundlegende Ausgangsregeln

Die vordefinierte Sicherheitsgruppe für den Agenten umfasst die folgenden ausgehenden Regeln.

[cols="3*"]
|===
| Protokoll | Hafen | Zweck 


| Alle TCP | Alle | Der gesamte ausgehende Verkehr 


| Alle UDP | Alle | Der gesamte ausgehende Verkehr 
|===


[[advanced-outbound-rules]]
=== Erweiterte Ausgangsregeln

Wenn Sie strenge Regeln für den ausgehenden Datenverkehr benötigen, können Sie die folgenden Informationen verwenden, um nur die Ports zu öffnen, die für die ausgehende Kommunikation durch den Agenten erforderlich sind.


NOTE: Die Quell-IP-Adresse ist der Agent-Host.

[cols="5*"]
|===
| Service | Protokoll | Hafen | Ziel | Zweck 


| API-Aufrufe und AutoSupport | HTTPS | 443 | Outbound-Internet und ONTAP Cluster-Management-LIF | API-Aufrufe an Azure, an ONTAP, an NetApp Data Classification und Senden von AutoSupport -Nachrichten an NetApp 


| API-Aufrufe | TCP | 8080 | Datenklassifizierung | Testen der Datenklassifizierungsinstanz während der Bereitstellung 


| DNS | UDP | 53 | DNS | Wird von der Konsole zur DNS-Auflösung verwendet 
|===