---
sidebar: sidebar 
permalink: reference-iam-ransomware-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin, 
summary: Ransomware Resilience bietet verschiedene Benutzerrollen zur Verwaltung des Zugriffs auf Einstellungen, Aktionen und Berichte. 
---
= Ransomware Resilience-Zugriffsrollen für die NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ransomware Resilience-Rollen bieten Benutzern Zugriff auf NetApp Ransomware Resilience. Ransomware Resilience unterstützt die folgenden Rollen:

*Grundrollen*

* Ransomware-Resilience-Administrator – Konfigurieren Sie die Ransomware-Resilience-Einstellungen; untersuchen Sie Verschlüsselungswarnungen und reagieren Sie darauf.
* Ransomware Resilience Viewer – Anzeigen von Verschlüsselungsvorfällen, Berichten und Erkennungseinstellungen


*Benutzerverhaltensaktivitätsrollen* link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["Erkennung verdächtiger Benutzeraktivitäten"^]-Warnmeldungen bieten Einblick in Daten wie Dateiaktivitätsereignisse; diese Warnmeldungen enthalten Dateinamen und vom Benutzer durchgeführte Dateiaktionen (wie Lesen, Schreiben, Löschen, Umbenennen). Um die Sichtbarkeit dieser Daten einzuschränken, können nur Benutzer mit diesen Rollen diese Warnmeldungen verwalten oder anzeigen.

* Ransomware Resilience-Benutzerverhaltensadministrator – Aktivieren Sie die Erkennung verdächtiger Benutzeraktivitäten, untersuchen Sie verdächtige Benutzeraktivitäten und reagieren Sie auf Warnungen zu verdächtigen Benutzeraktivitäten
* Ransomware Resilience-Benutzerverhaltensanzeige – Anzeigen von Warnungen zu verdächtigen Benutzeraktivitäten



NOTE: Benutzerverhaltensrollen sind keine eigenständigen Rollen. Sie sind dafür vorgesehen, den Administrator- oder Viewer-Rollen von Ransomware Resilience hinzugefügt zu werden. Weitere Informationen finden Sie unter <<Benutzerverhaltensrollen>>.

Ausführliche Beschreibungen der einzelnen Rollen finden Sie in den folgenden Tabellen.



[[baseline-roles]]
== Basisrollen

In der folgenden Tabelle werden die Aktionen beschrieben, die den Administrator- und Viewer-Rollen von Ransomware Resilience zur Verfügung stehen.

[cols="40,20a,20a"]
|===
| Funktion und Aktion | Ransomware-Resilienz-Administrator | Ransomware Resilience-Viewer 


| Dashboard und alle Registerkarten anzeigen  a| 
Ja
 a| 
Ja



| Aktualisieren Sie den Empfehlungsstatus auf dem Dashboard  a| 
Ja
 a| 
Nein



| Kostenlose Testversion starten  a| 
Ja
 a| 
Nein



| Ermittlung von Workloads initiieren  a| 
Ja
 a| 
Nein



| Neuermittlung von Workloads einleiten  a| 
Ja
 a| 
Nein



3+| *Auf der Registerkarte „Schützen“*: 


| Hinzufügen, Ändern oder Löschen von Schutzplänen für _Verschlüsselungs_richtlinien  a| 
Ja
 a| 
Nein



| Workloads schützen  a| 
Ja
 a| 
Nein



| Identifizieren Sie die Gefährdung sensibler Daten mit der Datenklassifizierung  a| 
Ja
 a| 
Nein



| Listen Sie Schutzpläne und Details auf  a| 
Ja
 a| 
Ja



| Auflisten von Schutzgruppen  a| 
Ja
 a| 
Ja



| Anzeigen von Schutzgruppendetails  a| 
Ja
 a| 
Ja



| Erstellen, Bearbeiten oder Löschen von Schutzgruppen  a| 
Ja
 a| 
Nein



| Daten herunterladen  a| 
Ja
 a| 
Ja



3+| *Auf der Registerkarte „Warnungen“*: 


| Anzeigen von Verschlüsselungswarnungen und Warnungsdetails  a| 
Ja
 a| 
Ja



| Verschlüsselungsvorfallstatus bearbeiten  a| 
Ja
 a| 
Nein



| Verschlüsselungsalarm zur Wiederherstellung markieren  a| 
Ja
 a| 
Nein



| Details zum Verschlüsselungsvorfall anzeigen  a| 
Ja
 a| 
Ja



| Verschlüsselungsvorfälle verwerfen oder beheben  a| 
Ja
 a| 
Nein



| Vollständige Liste der betroffenen Dateien im Verschlüsselungsereignis abrufen  a| 
Ja
 a| 
Nein



| Daten zu Verschlüsselungsereigniswarnungen herunterladen  a| 
Ja
 a| 
Ja



| Benutzer blockieren (mit Workload Security-Agent-Konfiguration)  a| 
Ja
 a| 
Nein



3+| *Auf der Registerkarte „Wiederherstellen“*: 


| Herunterladen der betroffenen Dateien vom Verschlüsselungsereignis  a| 
Ja
 a| 
Nein



| Workload nach Verschlüsselungsereignis wiederherstellen  a| 
Ja
 a| 
Nein



| Wiederherstellungsdaten aus dem Verschlüsselungsereignis herunterladen  a| 
Ja
 a| 
Ja



| Laden Sie Berichte vom Verschlüsselungsereignis herunter  a| 
Ja
 a| 
Ja



3+| *Auf der Registerkarte „Einstellungen“*: 


| Hinzufügen oder Ändern von Sicherungszielen  a| 
Ja
 a| 
Nein



| Auflisten der Sicherungsziele  a| 
Ja
 a| 
Ja



| Verbundene SIEM-Ziele anzeigen  a| 
Ja
 a| 
Ja



| SIEM-Ziele hinzufügen oder ändern  a| 
Ja
 a| 
Nein



| Bereitschaftsübung konfigurieren  a| 
Ja
 a| 
Nein



| Bereitschaftsübung starten, zurücksetzen oder bearbeiten  a| 
Ja
 a| 
Nein



| Status der Bereitschaftsübung überprüfen  a| 
Ja
 a| 
Ja



| Aktualisieren der Erkennungskonfiguration  a| 
Ja
 a| 
Nein



| Anzeigen der Erkennungskonfiguration  a| 
Ja
 a| 
Ja



3+| *Auf der Registerkarte „Berichte“*: 


| Berichte herunterladen  a| 
Ja
 a| 
Ja

|===


[[user-behavior-roles]]
== Benutzerverhaltensrollen

Um Einstellungen für verdächtiges Benutzerverhalten zu konfigurieren und auf Warnungen zu reagieren, muss ein Benutzer über die Administratorrolle „Ransomware Resilience-Benutzerverhalten“ verfügen. Um nur Warnungen zu verdächtigem Benutzerverhalten anzuzeigen, sollte ein Benutzer über die Rolle „Ransomware Resilience-Benutzerverhaltensanzeiger“ verfügen.

Benutzerverhaltensrollen sollten Benutzern mit bestehenden Administrator- oder Betrachterberechtigungen für Ransomware Resilience zugewiesen werden, die Zugriff auf link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["Einstellungen und Warnungen bei verdächtigen Benutzeraktivitäten"^] benötigen. Ein Benutzer mit der Ransomware Resilience Administratorrolle sollte beispielsweise die Ransomware Resilience Benutzerverhalten-Administratorrolle erhalten, um Benutzeraktivitätsagenten zu konfigurieren und Benutzer zu sperren oder zu entsperren. Die Ransomware Resilience Benutzerverhalten-Administratorrolle sollte nicht einem Ransomware Resilience Betrachter zugewiesen werden.


NOTE: Um die Erkennung verdächtiger Benutzeraktivitäten zu aktivieren, müssen Sie über die Administratorrolle der Konsolenorganisation verfügen.

In der folgenden Tabelle werden die Aktionen beschrieben, die für die Administrator- und Viewer-Rollen des Benutzerverhaltens von Ransomware Resilience verfügbar sind.

[cols="40,20a,20a"]
|===
| Funktion und Aktion | Ransomware Resilience-Benutzerverhaltensadministrator | Ransomware Resilience-Benutzerverhaltensanzeige 


3+| *Auf der Registerkarte „Einstellungen“*: 


| Erstellen, Ändern oder Löschen eines Benutzeraktivitätsagenten  a| 
Ja
 a| 
Nein



| Benutzerverzeichnis-Connector erstellen oder löschen  a| 
Ja
 a| 
Nein



| Datensammler anhalten oder fortsetzen  a| 
Ja
 a| 
Nein



| Führen Sie eine Übung zur Vorbereitung auf Datenschutzverletzungen durch  a| 
Ja
 a| 
Nein



3+| *Auf der Registerkarte „Schützen“*: 


| Hinzufügen, Ändern oder Löschen von Schutzplänen für Richtlinien zu _verdächtigem Benutzerverhalten_  a| 
Ja
 a| 
Nein



3+| *Auf der Registerkarte „Warnungen“*: 


| Anzeigen von Benutzeraktivitätswarnungen und Warnungsdetails  a| 
Ja
 a| 
Ja



| Bearbeiten des Vorfallstatus für Benutzeraktivitäten  a| 
Ja
 a| 
Nein



| Benutzeraktivitätswarnung zur Wiederherstellung markieren  a| 
Ja
 a| 
Nein



| Details zum Vorfall mit Benutzeraktivität anzeigen  a| 
Ja
 a| 
Ja



| Abweisen oder Lösen von Vorfällen im Zusammenhang mit Benutzeraktivitäten  a| 
Ja
 a| 
Nein



| Vollständige Liste der betroffenen Dateien nach verdächtigem Benutzer abrufen  a| 
Ja
 a| 
Ja



| Laden Sie Ereigniswarnungsdaten zu Benutzeraktivitäten herunter  a| 
Ja
 a| 
Ja



| Benutzer blockieren oder entsperren  a| 
Ja
 a| 
Nein



3+| *Auf der Registerkarte „Wiederherstellen“*: 


| Herunterladen betroffener Dateien für Benutzeraktivitätsereignisse  a| 
Ja
 a| 
Nein



| Wiederherstellen der Arbeitslast aus dem Benutzeraktivitätsereignis  a| 
Ja
 a| 
Nein



| Laden Sie Wiederherstellungsdaten aus dem Benutzeraktivitätsereignis herunter  a| 
Ja
 a| 
Ja



| Laden Sie Berichte zum Benutzeraktivitätsereignis herunter  a| 
Ja
 a| 
Ja

|===