---
sidebar: sidebar 
permalink: reference-agent-maint-console-proxy.html 
keywords: transparent proxy, connector certificate, agent maintenance console, proxy configuration, connector proxy. agent proxy 
summary: Sie können die Wartungskonsole des Konsolenagenten verwenden, um einen Konsolenagenten für die Verwendung eines transparenten Proxyservers zu konfigurieren. 
---
= Transparente Proxy-Befehle
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Wartungskonsole des Konsolenagenten verwenden, um einen Konsolenagenten für die Verwendung eines transparenten Proxyservers zu konfigurieren.



== Zugriff auf die Agenten-Wartungskonsole

Sie können vom Konsolenagent-Host aus auf die Wartungskonsole zugreifen.  Navigieren Sie zum folgenden Verzeichnis:

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


=== Hilfe zu jedem Befehl anzeigen

Um Hilfe zu einem Befehl anzuzeigen, fügen Sie an `--help` zum Befehl.  Um beispielsweise Hilfe für die `proxy add` Befehl, verwenden Sie den folgenden Befehl:

[source, cli]
----
./agent-maint-console proxy add --help
----


== Proxy abrufen

Der `proxy get` Der Befehl zeigt Informationen über die aktuelle Konfiguration des transparenten Proxy-Servers an.  Um die aktuelle Konfiguration des transparenten Proxy-Servers anzuzeigen, verwenden Sie folgenden Befehl:



=== Proxy-Abfragebeispiel

Um die aktuelle Konfiguration des transparenten Proxy-Servers anzuzeigen, verwenden Sie folgenden Befehl:

[source, cli]
----
./agent-maint-console proxy get
----


== Proxy hinzufügen

Der `proxy add` Der Befehl konfiguriert den Agenten zur Verwendung eines transparenten Proxy-Servers.



=== Parameter

`-c <certificate file>`

[role="quick-margin-para"]
Gibt den Pfad zur Zertifikatsdatei für den Proxy-Server an.  Die Zertifikatsdatei muss im PEM-Format vorliegen. Stellen Sie sicher, dass sich die Zertifikatsdatei im selben Verzeichnis wie der Befehl befindet, oder geben Sie den vollständigen Pfad zur Zertifikatsdatei an.



=== Beispiel zum Hinzufügen eines Proxys

Um einen transparenten Proxyserver hinzuzufügen, verwenden Sie den folgenden Befehl, wobei `/home/ubuntu/myCA1.pem` ist der Pfad zur Zertifikatsdatei für den Proxyserver.  Die Zertifikatsdatei muss im PEM-Format vorliegen:

[source, cli]
----
./agent-maint-console proxy add -c /home/ubuntu/myCA1.pem
----


== Proxy-Update

Der `proxy update` Mit diesem Befehl können Sie das Zertifikat eines transparenten Proxys aktualisieren.



=== Parameter

`-c <certificate file>`gibt den Pfad zur Zertifikatsdatei für den Proxy-Server an.  Die Zertifikatsdatei muss im PEM-Format vorliegen.

Stellen Sie sicher, dass sich die Zertifikatsdatei im selben Verzeichnis wie der Befehl befindet, oder geben Sie den vollständigen Pfad zur Zertifikatsdatei an.



=== Proxy-Update-Beispiel

Um das Zertifikat für einen transparenten Proxyserver zu aktualisieren, verwenden Sie den folgenden Befehl, wobei `/home/ubuntu/myCA1.pem` ist der Pfad zur neuen Zertifikatsdatei für den Proxyserver.  Die Zertifikatsdatei muss im PEM-Format vorliegen:

[source, cli]
----
./agent-maint-console proxy update -c /home/ubuntu/myCA1.pem
----


== Proxy entfernen

Der `proxy remove` Der Befehl entfernt die Konfiguration des transparenten Proxy-Servers vom Agenten.



=== Beispiel zum Entfernen eines Proxys

Um den transparenten Proxyserver zu entfernen, verwenden Sie den folgenden Befehl:

[source, cli]
----
./agent-maint-console proxy remove
----