---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: Deinstallieren Sie einen Console-Agenten, um Probleme zu beheben oder ihn dauerhaft vom Host zu entfernen. Die Schritte, die Sie verwenden müssen, hängen vom Bereitstellungsmodus ab, den Sie verwenden. Sobald Sie einen Console-Agenten aus Ihrer Umgebung entfernt haben, können Sie ihn aus der Console entfernen. 
---
= Deinstallieren und Entfernen eines Konsolenagenten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Deinstallieren Sie einen Console-Agenten, um Probleme zu beheben oder ihn dauerhaft vom Host zu entfernen. Die Schritte, die Sie verwenden müssen, hängen vom Bereitstellungsmodus ab, den Sie verwenden. Sobald Sie einen Console-Agenten aus Ihrer Umgebung entfernt haben, können Sie ihn aus der Console entfernen.



== Deinstallieren Sie den Agenten, wenn er über ausgehende Konnektivität verfügt

Wenn Sie den Standardmodus oder den eingeschränkten Modus verwenden (mit anderen Worten, der Agent-Host verfügt über eine ausgehende Konnektivität), sollten Sie die folgenden Schritte ausführen, um den Agenten zu deinstallieren.

.Schritte
. Stellen Sie eine Verbindung zur Linux-VM für den Agenten her.
. Führen Sie vom Linux-Host aus das Deinstallationsskript aus:
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ führt das Skript aus, ohne Sie zur Bestätigung aufzufordern.





== Deinstallieren Sie den Agenten, wenn er keine ausgehende Verbindung hat

Wenn Ihr Agent keine ausgehende Verbindung hat (zum Beispiel im privaten Modus), müssen Sie die Agentensoftware manuell vom Host entfernen.

.Schritt
. Stellen Sie eine Verbindung zur Linux-VM für den Konsolen-Agenten her.
. Führen Sie auf dem Linux-Host die folgenden Befehle aus:
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. Löschen Sie auf dem Linux-Host alte, nicht verwendete Container-Image-Dateien, um Speicherplatz im Verzeichnis /var für die Re-Installation freizugeben.
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




== Entfernen von Konsolenagenten aus der Konsole

Wenn Sie eine Agenten-VM gelöscht oder den Agenten deinstalliert haben, sollten Sie ihn aus der Liste der Agenten in der Konsole entfernen. Nach dem Löschen einer Agenten-VM oder der Deinstallation der Agentensoftware wird der Agent in der Konsole als *Getrennt* angezeigt.

Beachten Sie beim Entfernen eines Konsolenagenten Folgendes:

* Durch diese Aktion wird die virtuelle Maschine nicht gelöscht.
* Diese Aktion kann nicht rückgängig gemacht werden. Wenn Sie einen Konsolenagenten einmal entfernt haben, können Sie ihn nicht wieder hinzufügen.


.Schritte
. Wählen Sie *Administration > Agenten*.
. Auf der Seite *Übersicht* wählen Sie das Aktionsmenü für einen getrennten Agenten und wählen Sie *Agent entfernen*.
. Geben Sie zur Bestätigung den Namen des Agenten ein und wählen Sie dann *Entfernen*.

