---
sidebar: sidebar 
permalink: task-console-assistant.html 
keywords: bluexp,netapp console,console assistant,assistant,setup assistant,get started,quick start,first time user,first time setup,setup wizard 
summary: 'Wenn Sie die NetApp Console zum ersten Mal verwenden, führt Sie der Konsolenassistent durch den ersten Einrichtungsprozess.  Der Assistent unterstützt Sie beim Hinzufügen eines NetApp Support Site (NSS)-Kontos, eines Konsolenagenten, eines Clusters und einer Lizenz oder eines Abonnements und erleichtert Ihnen so den Einstieg in die Verwaltung Ihrer Daten.' 
---
= Erste Schritte mit dem NetApp Console Assistenten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie die NetApp Console (SaaS) zum ersten Mal mit der Rolle eines Organisationsadministrators verwenden, können Sie sich mithilfe des Console-Assistenten durch den Ersteinrichtungsprozess führen lassen. Der Assistent hilft Ihnen beim Hinzufügen eines NetApp Support Site (NSS)-Kontos, eines Console-Agenten, eines Clusters sowie einer Lizenz oder eines Abonnements und erleichtert Ihnen so den Einstieg in die Datenverwaltung.



[[required-roles-to-access-the-console-assistant]]
== Erforderliche Rollen für den Zugriff auf den Konsolenassistenten

Der Konsolenassistent ist nur für Benutzer mit der Rolle „Organisationsadministrator“ verfügbar.

Standardmäßig wird der Konsolenassistent auf der Startseite der NetApp Console für Erstbenutzer mit der Rolle „Organisationsadministrator“ angezeigt. Es bleibt so lange verfügbar, bis Sie die obligatorischen Aufgaben der Erstellung eines Konsolenagenten und des Hinzufügens eines Systems abgeschlossen haben.

Nutzen Sie den Assistenten, um diese Aufgaben zu erledigen, die die minimale Einrichtung Ihrer NetApp Console-Umgebung bereitstellen:

* Fügen Sie ein NetApp Support Site (NSS)-Konto hinzu.
+
link:task-adding-nss-accounts.html["Erfahren Sie, wie Sie ein NSS-Konto hinzufügen."]Die

* Stellen Sie eine Verbindung zu Ihrem Speichersystem her, indem Sie einen Console-Agenten einsetzen.
+
link:task-install-agent-on-prem.html["Erfahren Sie, wie Sie einen Console-Agenten lokal installieren."]

* Verwalten Sie ein Speichersystem durch Hinzufügen oder Erkennen eines Clusters
* Fügen Sie ein Marktplatzabonnement oder eine PAYGO-Lizenz hinzu.
+
link:https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html["Erfahren Sie, wie Sie Lizenzen und Abonnements hinzufügen."^]Die

* Informationen zu Datendiensten prüfen.

