---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: Nachdem Sie sich bei der NetApp Console angemeldet haben, können Sie sich von der webbasierten Konsole aus anmelden, um mit der Verwaltung Ihrer Daten- und Speicherinfrastruktur zu beginnen. 
---
= Melden Sie sich bei der NetApp Console an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie sich bei der NetApp Console angemeldet haben, können Sie sich von der webbasierten Konsole aus anmelden, um mit der Verwaltung Ihrer Daten- und Speicherinfrastruktur zu beginnen.

Nachdem Sie sich angemeldet haben, muss Ihr Console-Organisationsadministrator Ihr Benutzerkonto zu einer Organisation hinzufügen, bevor Sie auf Ressourcen zugreifen können. Wenn Sie sich anmelden, aber keine Ressourcen sehen, wenden Sie sich an Ihren Organisationsadministrator. link:task-user-settings.html#contact-admin["Wenden Sie sich an Ihren Organisationsadministrator"].

.Schritte
. Navigieren Sie zur NetApp Console-URL. Die URL hängt davon ab, welchen Modus der Console Ihre Organisation verwendet:
+
** *Standardmodus*: Öffnen Sie einen Webbrowser und gehen Sie zu https://console.netapp.com["NetApp Console"^].
** **Eingeschränkter Modus oder Privater Modus**: Öffnen Sie einen Webbrowser und gehen Sie zu der IP-Adresse, auf der der Console agent installiert ist.


. Geben Sie auf der Seite *Anmelden* die E-Mail-Adresse ein, die mit Ihrem Login verknüpft ist.
. Je nach dem mit Ihrer Anmeldung verknüpften Authentifizierungsverfahren werden Sie zur Eingabe Ihrer Anmeldedaten aufgefordert.
+
** Ihre vorhandenen Anmeldeinformationen für die NetApp Support Site (NSS)
** Ein NetApp Console mit Ihrer E-Mail-Adresse und einem Passwort
** Eine föderierte Verbindung, wenn Ihr Administrator die Identitätsföderation für Ihre Organisation eingerichtet hat



