---
sidebar: sidebar 
permalink: task-install-agent-aws-marketplace.html 
keywords: install connector, aws connector installation, aws connector, install connector in aws, bluexp, aws marketplace, manual install, create connector 
summary: Um einen Konsolenagenten aus dem AWS Marketplace zu erstellen, müssen Sie Ihr Netzwerk einrichten, AWS-Berechtigungen vorbereiten, die Instanzanforderungen überprüfen und dann den Konsolenagenten erstellen. 
---
= Erstellen Sie einen Konsolenagenten aus dem AWS Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie erstellen einen Konsolenagenten in AWS direkt vom AWS Marketplace.  Um einen Konsolenagenten aus dem AWS Marketplace zu erstellen, müssen Sie Ihr Netzwerk einrichten, AWS-Berechtigungen vorbereiten, die Instanzanforderungen überprüfen und dann den Konsolenagenten erstellen.

.Bevor Sie beginnen
* Sie sollten über einelink:concept-agents.html["Verständnis von Konsolenagenten"] .
* Sie sollten überprüfenlink:reference-limitations.html["Einschränkungen des Konsolenagenten"] .




== Schritt 1: Einrichten des Netzwerks

Stellen Sie sicher, dass der Netzwerkstandort für den Konsolenagenten die folgenden Anforderungen erfüllt, um Hybrid Cloud-Ressourcen zu verwalten.

VPC und Subnetz:: Wenn Sie den Konsolenagenten erstellen, müssen Sie die VPC und das Subnetz angeben, in dem er sich befinden soll.


Verbindungen zu Zielnetzwerken:: Der Konsolenagent erfordert eine Netzwerkverbindung zu dem Standort, an dem Sie Systeme erstellen und verwalten möchten.  Beispielsweise das Netzwerk, in dem Sie Cloud Volumes ONTAP -Systeme oder ein Speichersystem in Ihrer lokalen Umgebung erstellen möchten.


Ausgehender Internetzugang:: Der Netzwerkstandort, an dem Sie den Konsolenagenten bereitstellen, muss über eine ausgehende Internetverbindung verfügen, um bestimmte Endpunkte zu kontaktieren.


Vom Konsolenagenten kontaktierte Endpunkte:: Der Konsolenagent benötigt ausgehenden Internetzugang, um die folgenden Endpunkte zu kontaktieren und Ressourcen und Prozesse innerhalb Ihrer öffentlichen Cloud-Umgebung für den täglichen Betrieb zu verwalten.
+
--
Die unten aufgeführten Endpunkte sind alle CNAME-Einträge.

[cols="2a,1a"]
|===
| Endpunkte | Zweck 


 a| 
AWS-Dienste (amazonaws.com):

* CloudFormation
* Elastische Compute Cloud (EC2)
* Identitäts- und Zugriffsverwaltung (IAM)
* Schlüsselverwaltungsdienst (KMS)
* Sicherheitstokendienst (STS)
* Einfacher Speicherdienst (S3)

 a| 
Zur Verwaltung von AWS-Ressourcen.  Der Endpunkt hängt von Ihrer AWS-Region ab. https://docs.aws.amazon.com/general/latest/gr/rande.html["Weitere Einzelheiten finden Sie in der AWS-Dokumentation."^]



 a| 
\https://mysupport.netapp.com
 a| 
Um Lizenzinformationen zu erhalten und AutoSupport -Nachrichten an den NetApp Support zu senden.



 a| 
\https://signin.b2c.netapp.com
 a| 
So aktualisieren Sie die Anmeldeinformationen der NetApp Support Site (NSS) oder fügen der NetApp Console neue NSS-Anmeldeinformationen hinzu.



 a| 
\https://support.netapp.com
 a| 
Um Lizenzinformationen zu erhalten und AutoSupport -Nachrichten an den NetApp Support zu senden sowie um Software-Updates für Cloud Volumes ONTAP zu erhalten.



 a| 
\https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.bluexp.netapp.com \https://cdn.auth0.com
 a| 
Um Funktionen und Dienste innerhalb der NetApp Console bereitzustellen.



 a| 
\https://bluexpinfraprod.eastus2.data.azurecr.io \https://bluexpinfraprod.azurecr.io
 a| 
Um Bilder für Upgrades des Konsolenagenten zu erhalten.

* Wenn Sie einen neuen Agenten bereitstellen, testet die Validierungsprüfung die Konnektivität zu aktuellen Endpunkten. Wenn Sielink:reference-networking-saas-console-previous.html["vorherige Endpunkte"] , schlägt die Validierungsprüfung fehl. Um diesen Fehler zu vermeiden, überspringen Sie die Validierungsprüfung.
+
Obwohl die vorherigen Endpunkte weiterhin unterstützt werden, empfiehlt NetApp , Ihre Firewall-Regeln so schnell wie möglich auf die aktuellen Endpunkte zu aktualisieren. link:reference-networking-saas-console-previous.html#update-endpoint-list["Erfahren Sie, wie Sie Ihre Endpunktliste aktualisieren"] .

* Wenn Sie auf die aktuellen Endpunkte in Ihrer Firewall aktualisieren, funktionieren Ihre vorhandenen Agenten weiterhin.


|===
--


Proxyserver:: NetApp unterstützt sowohl explizite als auch transparente Proxy-Konfigurationen.  Wenn Sie einen transparenten Proxy verwenden, müssen Sie nur das Zertifikat für den Proxyserver angeben.  Wenn Sie einen expliziten Proxy verwenden, benötigen Sie auch die IP-Adresse und die Anmeldeinformationen.
+
--
* IP-Adresse
* Anmeldeinformationen
* HTTPS-Zertifikat


--


Häfen:: Es gibt keinen eingehenden Datenverkehr zum Konsolenagenten, es sei denn, Sie initiieren ihn oder er wird als Proxy zum Senden von AutoSupport Nachrichten von Cloud Volumes ONTAP an den NetApp Support verwendet.
+
--
* HTTP (80) und HTTPS (443) ermöglichen den Zugriff auf die lokale Benutzeroberfläche, die Sie in seltenen Fällen verwenden werden.
* SSH (22) wird nur benötigt, wenn Sie zur Fehlerbehebung eine Verbindung zum Host herstellen müssen.
* Eingehende Verbindungen über Port 3128 sind erforderlich, wenn Sie Cloud Volumes ONTAP -Systeme in einem Subnetz bereitstellen, in dem keine ausgehende Internetverbindung verfügbar ist.
+
Wenn Cloud Volumes ONTAP -Systeme keine ausgehende Internetverbindung zum Senden von AutoSupport Nachrichten haben, konfiguriert die Konsole diese Systeme automatisch für die Verwendung eines Proxyservers, der im Konsolenagenten enthalten ist.  Die einzige Voraussetzung besteht darin, sicherzustellen, dass die Sicherheitsgruppe des Konsolenagenten eingehende Verbindungen über Port 3128 zulässt.  Sie müssen diesen Port öffnen, nachdem Sie den Konsolenagenten bereitgestellt haben.



--


Aktivieren von NTP:: Wenn Sie NetApp Data Classification zum Scannen Ihrer Unternehmensdatenquellen verwenden möchten, sollten Sie sowohl auf dem Konsolenagenten als auch auf dem NetApp Data Classification -System einen Network Time Protocol (NTP)-Dienst aktivieren, damit die Zeit zwischen den Systemen synchronisiert wird. https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["Erfahren Sie mehr über die NetApp Datenklassifizierung"^]
+
--
Implementieren Sie diesen Netzwerkzugriff, nachdem Sie den Konsolenagenten erstellt haben.

--




== Schritt 2: AWS-Berechtigungen einrichten

Um eine Marktplatzbereitstellung vorzubereiten, erstellen Sie IAM-Richtlinien in AWS und ordnen Sie sie einer IAM-Rolle zu.  Wenn Sie den Konsolenagenten aus dem AWS Marketplace erstellen, werden Sie aufgefordert, diese IAM-Rolle auszuwählen.

.Schritte
. Melden Sie sich bei der AWS-Konsole an und navigieren Sie zum IAM-Dienst.
. Erstellen Sie eine Richtlinie:
+
.. Wählen Sie *Richtlinien > Richtlinie erstellen*.
.. Wählen Sie *JSON* und kopieren und fügen Sie den Inhalt deslink:reference-permissions-aws.html["IAM-Richtlinie für den Konsolenagenten"] .
.. Führen Sie die restlichen Schritte aus, um die Richtlinie zu erstellen.
+
Möglicherweise müssen Sie basierend auf den NetApp -Datendiensten, die Sie verwenden möchten, eine zweite Richtlinie erstellen.  Für Standardregionen sind die Berechtigungen auf zwei Richtlinien verteilt.  Aufgrund einer maximalen Zeichengrößenbeschränkung für verwaltete Richtlinien in AWS sind zwei Richtlinien erforderlich. link:reference-permissions-aws.html["Weitere Informationen zu IAM-Richtlinien für den Konsolenagenten"] .



. Erstellen Sie eine IAM-Rolle:
+
.. Wählen Sie *Rollen > Rolle erstellen*.
.. Wählen Sie *AWS-Dienst > EC2*.
.. Fügen Sie Berechtigungen hinzu, indem Sie die gerade erstellte Richtlinie anhängen.
.. Führen Sie die restlichen Schritte aus, um die Rolle zu erstellen.




.Ergebnis
Sie verfügen jetzt über eine IAM-Rolle, die Sie während der Bereitstellung vom AWS Marketplace aus mit der EC2-Instance verknüpfen können.



== Schritt 3: Überprüfen der Instanzanforderungen

Wenn Sie den Konsolenagenten erstellen, müssen Sie einen EC2-Instance-Typ auswählen, der die folgenden Anforderungen erfüllt.

CPU:: 8 Kerne oder 8 vCPUs
RAM:: 32 GB
AWS EC2-Instanztyp:: Ein Instanztyp, der die oben genannten CPU- und RAM-Anforderungen erfüllt.  Wir empfehlen t3.2xlarge.




== Schritt 4: Erstellen des Konsolenagenten

Erstellen Sie den Konsolenagenten direkt vom AWS Marketplace.

.Informationen zu diesem Vorgang
Durch Erstellen des Konsolenagenten aus dem AWS Marketplace wird eine EC2-Instanz in AWS mithilfe einer Standardkonfiguration bereitgestellt. link:reference-agent-default-config.html["Erfahren Sie mehr über die Standardkonfiguration für den Konsolenagenten"] .

.Bevor Sie beginnen
Folgendes sollten Sie haben:

* Eine VPC und ein Subnetz, das die Netzwerkanforderungen erfüllt.
* Eine IAM-Rolle mit einer angehängten Richtlinie, die die erforderlichen Berechtigungen für den Konsolenagenten enthält.
* Berechtigungen zum Abonnieren und Abbestellen des AWS Marketplace für Ihren IAM-Benutzer.
* Ein Verständnis der CPU- und RAM-Anforderungen für die Instanz.
* Ein Schlüsselpaar für die EC2-Instanz.


.Schritte
. Gehen Sie zum https://aws.amazon.com/marketplace/pp/prodview-jbay5iyfmu6ui["Auflistung des NetApp Console -Agenten im AWS Marketplace"^]
. Wählen Sie auf der Marketplace-Seite *Weiter zum Abonnieren* aus.
. Um die Software zu abonnieren, wählen Sie *Bedingungen akzeptieren*.
+
Der Abonnementvorgang kann einige Minuten dauern.

. Wählen Sie nach Abschluss des Abonnementvorgangs *Weiter zur Konfiguration*.
. Stellen Sie auf der Seite *Diese Software konfigurieren* sicher, dass Sie die richtige Region ausgewählt haben, und wählen Sie dann *Weiter zum Starten*.
. Wählen Sie auf der Seite *Diese Software starten* unter *Aktion auswählen* die Option *Über EC2 starten* und dann *Starten*.
+
Verwenden Sie die EC2-Konsole, um die Instanz zu starten und eine IAM-Rolle anzuhängen.  Dies ist mit der Aktion *Von Website starten* nicht möglich.

. Folgen Sie den Anweisungen zum Konfigurieren und Bereitstellen der Instanz:
+
** *Name und Tags*: Geben Sie einen Namen und Tags für die Instanz ein.
** *Anwendungs- und Betriebssystem-Images*: Überspringen Sie diesen Abschnitt.  Der Konsolenagent AMI ist bereits ausgewählt.
** *Instanztyp*: Wählen Sie je nach regionaler Verfügbarkeit einen Instanztyp, der die RAM- und CPU-Anforderungen erfüllt (t3.2xlarge ist vorausgewählt und empfohlen).
** *Schlüsselpaar (Anmeldung)*: Wählen Sie das Schlüsselpaar aus, das Sie für eine sichere Verbindung mit der Instanz verwenden möchten.
** *Netzwerkeinstellungen*: Bearbeiten Sie die Netzwerkeinstellungen nach Bedarf:
+
*** Wählen Sie die gewünschte VPC und das gewünschte Subnetz.
*** Geben Sie an, ob die Instanz eine öffentliche IP-Adresse haben soll.
*** Geben Sie Sicherheitsgruppeneinstellungen an, die die erforderlichen Verbindungsmethoden für die Konsolen-Agenteninstanz aktivieren: SSH, HTTP und HTTPS.
+
link:reference-ports-aws.html["Sicherheitsgruppenregeln für AWS anzeigen"] .



** *Speicher konfigurieren*: Behalten Sie die Standardgröße und den Standarddatenträgertyp für das Stammvolume bei.
+
Wenn Sie die Amazon EBS-Verschlüsselung auf dem Stammvolume aktivieren möchten, wählen Sie *Erweitert*, erweitern Sie *Volume 1*, wählen Sie *Verschlüsselt* und wählen Sie dann einen KMS-Schlüssel.

** *Erweiterte Details*: Wählen Sie unter *IAM-Instanzprofil* die IAM-Rolle aus, die die erforderlichen Berechtigungen für den Konsolenagenten enthält.
** *Zusammenfassung*: Überprüfen Sie die Zusammenfassung und wählen Sie *Instanz starten*.
+
AWS startet den Konsolenagenten mit den angegebenen Einstellungen und der Konsolenagent wird in etwa zehn Minuten ausgeführt.



+

NOTE: Wenn die Installation fehlschlägt, können Sie Protokolle und einen Bericht anzeigen, die Ihnen bei der Fehlerbehebung helfen.link:task-troubleshoot-agent.html#troubleshoot-installation["Erfahren Sie, wie Sie Installationsprobleme beheben."]

. Öffnen Sie einen Webbrowser auf einem Host, der über eine Verbindung zur virtuellen Maschine des Konsolen-Agenten und zur URL des Konsolen-Agenten verfügt.
. Richten Sie nach der Anmeldung den Konsolenagenten ein:
+
.. Geben Sie die Konsolenorganisation an, die mit dem Konsolenagenten verknüpft werden soll.
.. Geben Sie einen Namen für das System ein.
.. Lassen Sie unter *Arbeiten Sie in einer sicheren Umgebung?* den eingeschränkten Modus deaktiviert.
+
Lassen Sie den eingeschränkten Modus deaktiviert, um die Konsole im Standardmodus zu verwenden.  Sie sollten den eingeschränkten Modus nur aktivieren, wenn Sie über eine sichere Umgebung verfügen und dieses Konto von den Backend-Diensten der Konsole trennen möchten.  Wenn das der Fall ist,link:task-quick-start-restricted-mode.html["Befolgen Sie die Schritte, um mit der NetApp Console im eingeschränkten Modus zu beginnen"] .

.. Wählen Sie *Los geht's*.




.Ergebnis
Der Konsolenagent ist jetzt installiert und mit Ihrer Konsolenorganisation eingerichtet.

Öffnen Sie einen Webbrowser und gehen Sie zu https://console.netapp.com["NetApp Console"^] um den Konsolenagenten mit der Konsole zu verwenden.

Wenn Sie Amazon S3-Buckets im selben AWS-Konto haben, in dem Sie den Konsolenagenten erstellt haben, wird auf der Seite *Systeme* automatisch eine Amazon S3-Arbeitsumgebung angezeigt. https://docs.netapp.com/us-en/storage-management-s3-storage/index.html["Erfahren Sie, wie Sie S3-Buckets über die NetApp Console verwalten"^]
