---
sidebar: sidebar 
permalink: task-maintain-agents.html 
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, connector, connector health 
summary: Die Wartung des Betriebssystems auf dem Agent-Host liegt in Ihrer Verantwortung.  Sie sollten beispielsweise Sicherheitsupdates auf das Betriebssystem auf dem Konsolenagent-Host anwenden, indem Sie die Standardverfahren Ihres Unternehmens zur Betriebssystemverteilung befolgen. 
---
= Die VM für einen manuell installierten Konsolenagenten verwalten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei der manuellen Installation eines Console-Agenten liegt die Wartung des Betriebssystems auf dem Agentenhost in Ihrer (des Kunden) Verantwortung. Beispielsweise sollten Sie (der Kunde) Sicherheitsupdates für das Betriebssystem auf dem Agentenhost anwenden, indem Sie die Standardverfahren Ihres Unternehmens für die Betriebssystemverteilung befolgen.



== Wenden Sie Betriebssystemaktualisierungen auf dem Agentenhost an

Wenden Sie Betriebssystem-Sicherheitspatches an, ohne die Agent-Hostdienste zu stoppen.

Um die Kompatibilität mit unterstützten Konfigurationen zu gewährleisten, sollten Sie verhindern, dass Docker oder Podman während routinemäßiger Betriebssystem-Patches aktualisiert werden. Dies können Sie tun, indem Sie Docker oder Podman entweder vorübergehend während Updates ausschließen oder den Paketmanager dauerhaft so konfigurieren, dass Docker- oder Podman-Updates übersprungen werden.

Im Folgenden finden Sie Beispiele, wie Sie Docker- oder Podman-Updates für verschiedene Linux-Distributionen ausschließen können. Konsultieren Sie die Dokumentation Ihrer Linux-Distribution für die aktuellsten Anweisungen zum Ausschließen von Paketen von Updates.

.Podman-Beispiel
[source, bash]
----
sudo yum update --exclude=podman
sudo yum upgrade
----
.Docker-Beispiel
[source, bash]
----
sudo apt-mark hold docker-ce docker-ce-cli containerd.io
sudo apt update
sudo apt upgrade
----


== VM- oder Instanztyp

Wenn Sie einen Konsolenagenten aus der Konsole erstellen, stellt dieser eine VM-Instanz mit einer Standardkonfiguration bei Ihrem Cloud-Anbieter bereit.  Wechseln Sie nach dem Erstellen des Agenten nicht zu einer kleineren VM-Instanz mit weniger CPU oder RAM.

In der folgenden Tabelle sind die CPU- und RAM-Anforderungen aufgeführt:

CPU:: 8 Kerne oder 8 vCPUs
RAM:: 32 GB


link:reference-agent-default-config.html["Erfahren Sie mehr über die Standardkonfiguration für den Agenten"] .



== Überwachen des Agenten

Die Konsole benachrichtigt Sie, wenn die Agent-VM fehlerhaft ist, beispielsweise bei Problemen mit Speicherplatz, RAM und CPU.  Überwachen Sie diese Benachrichtigungen im Benachrichtigungscenter in der Konsole oder konfigurieren Sie E-Mail-Benachrichtigungen.  Gelegentliche Erhöhungen des Speicherplatzes, des Arbeitsspeichers oder der CPU-Auslastung sind normal. Wenn dies jedoch häufig vorkommt, sollten Sie Maßnahmen zur Behebung des Problems ergreifen.

Beispielsweise benachrichtigt Sie die Konsole, wenn eine Agentenressource (CPU, RAM oder Festplattenspeicher) 30 Minuten lang hintereinander 90 % ihrer Gesamtkapazität überschreitet.  Wenn die Ressourcennutzung anschließend unter diesen Schwellenwert fällt, wird die Benachrichtigung im Benachrichtigungscenter als behoben (grün) angezeigt.


NOTE: Wenden Sie sich an den NetApp Support, wenn Sie Fragen zur Modifizierung Ihrer Agenten-VM haben.

link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#notification-center["Erfahren Sie mehr."^]

[cols="47,47"]
|===
| Benachrichtigung | Handlungsbedarf 


| Der Speicherplatz ist zu groß | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["Lesen Sie den NetApp Knowledge Base-Artikel"^] . 


| Die CPU-Auslastung ist zu hoch | Erhöhen Sie die CPU-Größe der Agent-VM bei Ihrem Cloud-Anbieter oder vor Ort, je nachdem, wo Sie sie installiert haben.  Alternativ können Sie zusätzliche Agenten erstellen und die Arbeitslast auf mehrere Agenten verteilen.  Die RAM-Auslastung kann je nach Umgebung, ONTAP Workloads, Anzahl der Cloud Volumes ONTAP Systeme und den von Ihnen verwendeten Datendiensten variieren. 


| Die RAM-Auslastung ist zu hoch | Erhöhen Sie den RAM der Agent-VM bei Ihrem Cloud-Anbieter oder vor Ort, je nachdem, wo Sie sie installiert haben.  Alternativ können Sie zusätzliche Agenten erstellen und die Arbeitslast auf mehrere Agenten verteilen.  Die RAM-Auslastung kann je nach Umgebung, ONTAP Workloads, Anzahl der Cloud Volumes ONTAP Systeme und den von Ihnen verwendeten Datendiensten variieren. 
|===


== Stoppen und Starten der Agent-VM

Stoppen und starten Sie die Agent-VM bei Bedarf über die Konsole Ihres Cloud-Anbieters oder über standardmäßige Verfahren vor Ort.

link:concept-agents.html#agents-must-be-operational-at-all-times["Beachten Sie, dass der Konsolenagent jederzeit betriebsbereit sein muss"] .



== Herstellen einer Verbindung mit der Linux-VM

Wenn Sie eine Verbindung mit der Linux-VM herstellen müssen, auf der der Agent ausgeführt wird, verwenden Sie die Konnektivitätsoptionen Ihres Cloud-Anbieters.

AWS:: Wenn Sie die Agenteninstanz in AWS erstellen, geben Sie einen AWS-Zugriffsschlüssel und einen geheimen Schlüssel an.  Sie können dieses Schlüsselpaar verwenden, um per SSH auf die Instanz zuzugreifen.  Verwenden Sie den Benutzernamen „ubuntu“ für die EC2-Linux-Instanz.  Verwenden Sie für Agenten, die vor Mai 2023 erstellt wurden, den Benutzernamen „ec2-user“.
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS Docs: Verbinden Sie sich mit Ihrer Linux-Instance"^]

--
Azurblau:: Wenn Sie die Agent-VM in Azure erstellen, geben Sie einen Benutzernamen an und wählen die Authentifizierung mit einem Kennwort oder einem öffentlichen SSH-Schlüssel.  Verwenden Sie die von Ihnen gewählte Authentifizierungsmethode, um eine Verbindung mit der VM herzustellen.
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure-Dokumente: SSH in Ihre VM"^]

--
Google Cloud:: Sie können keine Authentifizierungsmethode angeben, wenn Sie einen Agenten in Google Cloud erstellen.  Sie können jedoch über die Google Cloud Console oder die Google Cloud CLI (gcloud) eine Verbindung zur Linux-VM-Instanz herstellen.
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs: Verbindung zu Linux-VMs herstellen"^]

--

