---
sidebar: sidebar 
permalink: task-federation-verify-domain.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: Wenn Sie eine Verbindung mit einer anderen Domain als Ihrer E-Mail-Domain herstellen möchten, müssen Sie zunächst nachweisen, dass Sie Inhaber dieser Domain sind. Sie können nur verifizierte Domains für die Föderation verwenden. 
---
= E-Mail-Domäne für die Föderation in der NetApp Console verifizieren
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie eine Verbindung mit einer anderen Domain als Ihrer E-Mail-Domain herstellen möchten, müssen Sie zunächst nachweisen, dass Sie Inhaber dieser Domain sind. Sie können nur verifizierte Domains für die Föderation verwenden.

.Erforderliche Rollen
Die Administratorrolle der Föderation ist erforderlich, um Föderationen zu erstellen und zu verwalten. Mit dem Föderations-Viewer kann die Föderationsseite angezeigt werden. link:reference-iam-predefined-roles.html["Erfahren Sie mehr über Zugriffsrollen."]

Zur Überprüfung Ihrer Domäne müssen Sie den DNS-Einstellungen Ihrer Domäne einen TXT-Eintrag hinzufügen.  Dieser Datensatz dient als Nachweis dafür, dass Sie der Eigentümer der Domäne sind, und ermöglicht der NetApp Console, der Domäne für die Föderation zu vertrauen.  Möglicherweise müssen Sie sich mit Ihrem IT- oder Netzwerkadministrator abstimmen, um diesen Schritt abzuschließen.

Wenn Sie beispielsweise Microsoft Entra ID verwenden, können Sie die Schritte in der Microsoft-Dokumentation  https://learn.microsoft.com/en-us/entra/fundamentals/add-custom-domain["Fügen Sie eine Domäne mit Microsoft Entra ID hinzu"^] befolgen.

.Schritte
. Wählen Sie *Verwaltung > Identität und Zugriff*.
. Wählen Sie *Föderation* aus, um die Seite *Föderationen* anzuzeigen.
. Wählen Sie *Neue Föderation konfigurieren*.
. Wählen Sie *Domänenbesitz bestätigen*.
. Geben Sie die Domäne ein, die Sie verifizieren möchten, und wählen Sie *Weiter*.
. Kopieren Sie den bereitgestellten TXT-Eintrag.
. Gehen Sie zu den DNS-Einstellungen Ihrer Domäne und konfigurieren Sie den TXT-Wert, der als TXT-Eintrag für Ihre Domäne bereitgestellt wurde.  Arbeiten Sie bei Bedarf mit Ihrem IT- oder Netzwerkadministrator zusammen.
. Nachdem der TXT-Eintrag hinzugefügt wurde, kehren Sie zur Konsole zurück und wählen Sie *Überprüfen*.

