---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, service account, member, role, permissions, organization, project, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions 
summary: Verwalten Sie die Mitglieder Ihrer Organisation, um Berechtigungen auf verschiedenen Ebenen der Ressourcenhierarchie Ihrer Organisation bereitzustellen. 
---
= Fügen Sie Benutzer zu einer NetApp Console Organisation hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Innerhalb der Konsole gewähren Sie Benutzern Zugriff auf Projekte oder Ordner entsprechend einer Zugriffsrolle. Eine Zugriffsrolle enthält eine Reihe von Berechtigungen, die es einem Mitglied (Benutzer oder Dienstkonto) ermöglichen, bestimmte Aktionen auf der zugewiesenen Ebene der Ressourcenhierarchie durchzuführen.

.Erforderliche Zugriffsrollen
Super-Admin, Organisations-Admin oder Ordner- bzw. Projekt-Admin (für die von ihnen verwalteten Ordner und Projekte). link:reference-iam-predefined-roles.html["Informationen zu Zugriffsrollen"]Die



== Verstehen Sie, wie der Zugriff in der NetApp Console gewährt wird.

Die NetApp Console verwendet rollenbasierte Zugriffskontrolle (RBAC) zur Verwaltung von Berechtigungen. Weisen Sie Benutzern Rollen einzeln oder über föderierte Gruppen zu. Jede Rolle definiert die zulässigen Aktionen für bestimmte Ressourcen.

Beachten Sie Folgendes bezüglich der Zugriffsgewährung in der NetApp Console:

* Alle Benutzer müssen sich zunächst bei der NetApp Console registrieren, bevor ihnen Zugriff auf Ressourcen gewährt werden kann.
* Sie müssen jedem Benutzer in der Konsole explizit eine Rolle zuweisen, bevor er auf Ressourcen zugreifen kann, selbst wenn er Mitglied einer Verbundgruppe ist, der eine Rolle zugewiesen wurde.
* Sie können Dienstkonten direkt über die Konsole hinzufügen und ihnen Rollen zuweisen.




== Fügen Sie Ihrer Organisation Mitglieder hinzu

Die NetApp Console unterstützt drei Arten von Mitgliedern: Benutzerkonten, Dienstkonten und Verbundgruppen.

Benutzer müssen sich bei der NetApp Console registrieren, bevor Sie sie hinzufügen und ihnen eine Rolle zuweisen können, selbst wenn sie Mitglied einer Verbundgruppe sind. Dienstkonten können direkt in der Konsole erstellt werden.

Alle Mitglieder müssen mindestens eine Rolle explizit zugewiesen bekommen haben, um auf Ressourcen zugreifen zu können.

Beim Hinzufügen eines Mitglieds wählen Sie die Ressourcenebene (Organisation, Ordner oder Projekt) und weisen Sie eine oder mehrere Rollen mit den erforderlichen Berechtigungen zu.



=== Einen Benutzer hinzufügen

Benutzer registrieren sich für die NetApp Console, aber ein Organisationsadministrator, Ordner- oder Projektadministrator muss sie einer Organisation, einem Ordner oder einem Projekt hinzufügen, damit sie auf Ressourcen zugreifen können.

.Bevor Sie beginnen:
Der Benutzer muss sich bereits für die NetApp Console registriert haben. Falls sie sich noch nicht angemeldet haben, leiten Sie sie bitte weiter zu link:task-sign-up-saas.html["Registrieren Sie sich für die NetApp Console."]


NOTE: Wenn Sie einen Benutzer hinzufügen, der Teil einer Verbundgruppe ist, stellen Sie sicher, dass sich der Benutzer bereits bei der NetApp Console registriert hat und ihm explizit eine Rolle in der Console zugewiesen wurde. NetApp empfiehlt, eine minimale Zugriffsrolle wie z. B. „Organisationsbetrachter“ zuzuweisen.

.Schritte
. Wählen Sie *Verwaltung > Identität und Zugriff*.
. Wählen Sie *Mitglieder* aus.
. Wählen Sie *Mitglied hinzufügen*.
. Behalten Sie für *Mitgliedstyp* die Auswahl von *Benutzer* bei.
. Geben Sie bei *E-Mail des Benutzers* die E-Mail-Adresse des Benutzers ein, die mit der von ihm erstellten Anmeldung verknüpft ist.
. Verwenden Sie den Abschnitt *Wählen Sie eine Organisation, einen Ordner oder ein Projekt aus*, um die Ebene Ihrer Ressourcenhierarchie auszuwählen, für die das Mitglied Berechtigungen haben soll.
+
Beachten Sie Folgendes:

+
** Sie können nur die Ordner und Projekte auswählen, für die Sie die entsprechenden Berechtigungen besitzen.
** Wenn Sie eine Organisation oder einen Ordner auswählen, erteilen Sie dem Mitglied Berechtigungen für alle darin enthaltenen Inhalte.
** Sie können die Rolle *Organisationsadministrator* nur auf Organisationsebene zuweisen.


. *Wählen Sie eine Kategorie* und dann eine *Rolle* aus, die dem Mitglied Berechtigungen für die Ressourcen erteilt, die mit der von Ihnen ausgewählten Organisation, dem Ordner oder dem Projekt verknüpft sind.
+
link:reference-iam-predefined-roles.html["Informationen zu Zugriffsrollen"] .

. Um Zugriff auf weitere Ordner, Projekte oder Rollen zu gewähren, wählen Sie *Rolle hinzufügen*, wählen Sie die Ordner-, Projekt- oder Rollenkategorie und anschließend eine Rolle aus.
. Wählen Sie *Hinzufügen*.
+
Die Konsole sendet dem Benutzer eine E-Mail mit Anweisungen.





=== Hinzufügen eines Dienstkontos

Dienstkonten ermöglichen die Automatisierung von Aufgaben und die sichere Verbindung mit Console-APIs. Wählen Sie eine Client-ID und ein Client-Geheimnis für einfache Setups oder JWT (JSON Web Token) für eine höhere Sicherheit in automatisierten oder Cloud-nativen Umgebungen. Wählen Sie die Methode, die Ihren Sicherheitsanforderungen entspricht.

.Bevor Sie beginnen:
Bereiten Sie für die JWT-Authentifizierung Ihren öffentlichen Schlüssel oder Ihr Zertifikat vor.

.Schritte
. Wählen Sie *Verwaltung > Identität und Zugriff*.
. Wählen Sie *Mitglieder* aus.
. Wählen Sie *Mitglied hinzufügen*.
. Wählen Sie für *Mitgliedstyp* *Dienstkonto* aus.
. Geben Sie einen Namen für das Dienstkonto ein.
. Um die JWT-Authentifizierung zu verwenden, wählen Sie *Private-Key-JWT-Authentifizierung verwenden* und laden Sie Ihren öffentlichen RSA-Schlüssel oder Ihr Zertifikat hoch. Überspringen, falls Client-ID und Client-Geheimnis verwendet werden.
+
Ihr X.509-Zertifikat. Es muss im PEM-, CRT- oder CER-Format vorliegen.

+
.. Richten Sie Ablaufbenachrichtigungen für Ihr Zertifikat ein.  Sie haben die Wahl zwischen sieben Tagen oder 30 Tagen.  Ablaufbenachrichtigungen werden per E-Mail versendet und Benutzern mit der Rolle „Super-Admin“ oder „Org-Admin“ in der Konsole angezeigt.


. Verwenden Sie den Abschnitt *Wählen Sie eine Organisation, einen Ordner oder ein Projekt aus*, um die Ebene Ihrer Ressourcenhierarchie auszuwählen, für die das Mitglied Berechtigungen haben soll.
+
Beachten Sie Folgendes:

+
** Sie können nur aus den Ordnern und Projekten auswählen, für die Sie Berechtigungen haben.
** Durch die Auswahl einer Organisation oder eines Ordners erhält das Mitglied Zugriff auf alle Inhalte.
** Sie können die Rolle *Organisationsadministrator* nur auf Organisationsebene zuweisen.


. Wählen Sie eine *Kategorie* und anschließend eine *Rolle* aus, die dem Mitglied Berechtigungen für die Ressourcen in der von Ihnen ausgewählten Organisation, dem Ordner oder dem Projekt erteilt.
+
link:reference-iam-predefined-roles.html["Informationen zu Zugriffsrollen"] .

. Um Zugriff auf weitere Ordner, Projekte oder Rollen zu gewähren, wählen Sie *Rolle hinzufügen*, wählen Sie die Ordner-, Projekt- oder Rollenkategorie und anschließend eine Rolle aus.
. Wenn Sie sich nicht für die Verwendung der JWT-Authentifizierung entschieden haben, laden Sie die Client-ID und das Client-Geheimnis herunter oder kopieren Sie sie.
+
Die Konsole zeigt das Client-Geheimnis nur einmal an. Sicher kopieren; falls Sie es verlieren, können Sie es später wiederherstellen.

. Wenn Sie die JWT-Authentifizierung gewählt haben, laden Sie die Client-ID und die JWT-Zielgruppe herunter oder kopieren Sie sie. Die Konsole zeigt diese Informationen nur einmal an und erlaubt es Ihnen nicht, sie später abzurufen.
. Wählen Sie *Schließen*.




== Fügen Sie Ihrer Organisation eine föderierte Gruppe hinzu.

Sie können eine föderierte Gruppe von Ihrem Identitätsanbieter (IdP) zu Ihrer Organisation hinzufügen und ihr eine oder mehrere Rollen zuweisen. Die Mitglieder der föderierten Gruppe erben die Rollen, die Sie der Gruppe in der Konsole zuweisen.


IMPORTANT: Wenn Sie der Konsole eine Verbundgruppe hinzufügen und ihr eine Rolle zuweisen, können nur Benutzer, die Mitglieder dieser Gruppe in Ihrem IdP sind und sich bereits für die NetApp Console registriert und explizit eine Rolle in der Konsole zugewiesen bekommen haben, auf Ressourcen zugreifen. NetApp empfiehlt, diesen Benutzern eine Rolle mit minimalen Zugriffsrechten, wie zum Beispiel Organization viewer, zuzuweisen.

Bevor Sie einer föderierten Gruppe eine Rolle zuweisen können, stellen Sie Folgendes sicher:

* Richten Sie eine Föderation zwischen Ihrem IdP und der Konsole ein. link:concept-federation.html["Erfahren Sie, wie Sie eine Föderation einrichten."]
* Die Gruppe muss bereits in Ihrem Identitätsanbieter existieren und über App-Zugriff auf die Konsole verfügen.


.Schritte
. Wählen Sie *Verwaltung > Identität und Zugriff*.
. Wählen Sie *Mitglieder* aus.
. Wählen Sie *Mitglied hinzufügen*.
. Wählen Sie unter *Mitgliedstyp* die Option *Verbundgruppe*.
. Wählen Sie den Verband aus, dem die Gruppe angehört.
. Geben Sie unter *Gruppenname* den genauen Namen der Gruppe in Ihrem IdP ein.
. Verwenden Sie den Abschnitt *Wählen Sie eine Organisation, einen Ordner oder ein Projekt aus*, um die Ebene Ihrer Ressourcenhierarchie auszuwählen, für die das Mitglied Berechtigungen haben soll.
+
Beachten Sie Folgendes:

+
** Sie können nur aus den Ordnern und Projekten auswählen, für die Sie Berechtigungen haben.
** Durch die Auswahl einer Organisation oder eines Ordners erhält das Mitglied Zugriff auf alle Inhalte.
** Sie können die Rolle *Organisationsadministrator* nur auf Organisationsebene zuweisen.


. Wählen Sie eine *Kategorie* und anschließend eine *Rolle* aus, die dem Mitglied Berechtigungen für die Ressourcen in der von Ihnen ausgewählten Organisation, dem Ordner oder dem Projekt erteilt.
+
link:reference-iam-predefined-roles.html["Informationen zu Zugriffsrollen"] .

. Um Zugriff auf weitere Ordner, Projekte oder Rollen zu gewähren, wählen Sie *Rolle hinzufügen*, wählen Sie die Ordner-, Projekt- oder Rollenkategorie und anschließend eine Rolle aus.




== Ähnliche Informationen

* link:concept-identity-and-access-management.html["Erfahren Sie mehr über Identitäts- und Zugriffsmanagement in der NetApp Console"]
* link:task-iam-get-started.html["Erste Schritte mit Identität und Zugriff"]
* link:reference-iam-predefined-roles.html["NetApp Console"]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["Erfahren Sie mehr über die API für Identität und Zugriff"^]

