---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: 'Abhängig von den Aktionen, die Sie in der Konsole ausgeführt haben, haben Sie möglicherweise ONTAP Anmeldeinformationen und Anmeldeinformationen für die NetApp Support Site (NSS) mit Ihrer Benutzeranmeldung verknüpft.  Sie können diese Anmeldeinformationen anzeigen und verwalten, nachdem Sie sie verknüpft haben.  Wenn Sie beispielsweise das Kennwort für diese Anmeldeinformationen ändern, müssen Sie das Kennwort in der Konsole aktualisieren.' 
---
= Verwalten Sie die mit Ihrer NetApp Konsolenanmeldung verknüpften Anmeldeinformationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Abhängig von den Aktionen, die Sie in der Konsole ausgeführt haben, haben Sie möglicherweise ONTAP Anmeldeinformationen und Anmeldeinformationen für die NetApp Support Site (NSS) mit Ihrer Benutzeranmeldung verknüpft.  Sie können diese Anmeldeinformationen anzeigen und verwalten, nachdem Sie sie verknüpft haben.  Wenn Sie beispielsweise das Kennwort für diese Anmeldeinformationen ändern, müssen Sie das Kennwort in der Konsole aktualisieren.



== ONTAP -Anmeldeinformationen

Benutzer benötigen ONTAP Administratoranmeldeinformationen, um ONTAP Cluster in der Konsole zu erkennen.  Der Zugriff auf den ONTAP System Manager hängt jedoch davon ab, ob Sie einen Konsolenagenten verwenden oder nicht.

.Ohne einen Konsolenagenten
Benutzer werden aufgefordert, ihre ONTAP Anmeldeinformationen einzugeben, um auf den ONTAP System Manager für den Cluster zuzugreifen.  Benutzer können diese Anmeldeinformationen in der Konsole speichern, sodass sie nicht jedes Mal aufgefordert werden, sie einzugeben.  Benutzeranmeldeinformationen sind nur für den jeweiligen Benutzer sichtbar und können auf der Seite „Benutzeranmeldeinformationen“ verwaltet werden.

.Mit einem Konsolenagenten
Standardmäßig werden Benutzer nicht aufgefordert, ihre ONTAP Anmeldeinformationen einzugeben, um auf den ONTAP System Manager zuzugreifen.  Ein Konsolenadministrator (mit der Rolle „Organisationsadministrator“) kann die Konsole jedoch so konfigurieren, dass Benutzer aufgefordert werden, ihre ONTAP Anmeldeinformationen einzugeben.  Wenn diese Einstellung aktiviert ist, müssen Benutzer jedes Mal ihre ONTAP Anmeldeinformationen eingeben.

link:task-ontap-access-agent.html["Erfahren Sie mehr."^]



== NSS -Anmeldeinformationen

Die mit Ihrer NetApp Console-Anmeldung verknüpften NSS-Anmeldeinformationen ermöglichen die Support-Registrierung, das Fallmanagement und den Zugriff auf Digital Advisor.

* Wenn Sie auf *Support > Ressourcen* zugreifen und sich für den Support registrieren, werden Sie aufgefordert, NSS-Anmeldeinformationen mit Ihrem Login zu verknüpfen.
+
Dadurch wird Ihre Organisation oder Ihr Konto für den Support registriert und der Supportanspruch aktiviert.  Nur ein Benutzer in Ihrer Organisation muss seinem Login ein NetApp Support Site-Konto zuordnen, um sich für den Support zu registrieren und den Supportanspruch zu aktivieren.  Nachdem dies abgeschlossen ist, wird auf der Seite *Ressourcen* angezeigt, dass Ihr Konto für den Support registriert ist.

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["Erfahren Sie, wie Sie sich für den Support registrieren"^]

* Wenn Sie auf *Administration > Support > Fallmanagement* zugreifen, werden Sie aufgefordert, Ihre NSS-Anmeldeinformationen einzugeben, falls Sie dies nicht bereits getan haben.  Auf dieser Seite können Sie die mit Ihrem NSS-Konto und Ihrem Unternehmen verbundenen Supportfälle erstellen und verwalten.
* Wenn Sie in der Konsole auf Digital Advisor zugreifen, werden Sie aufgefordert, sich bei Digital Advisor anzumelden, indem Sie Ihre NSS-Anmeldeinformationen eingeben.


Beachten Sie Folgendes zum NSS-Konto, das mit Ihrer Anmeldung verknüpft ist:

* Das Konto wird auf Benutzerebene verwaltet, was bedeutet, dass es für andere Benutzer, die sich anmelden, nicht sichtbar ist.
* Pro Benutzer kann nur ein NSS-Konto mit Digital Advisor und Support-Fallmanagement verknüpft sein.
* Wenn Sie versuchen, ein NetApp Support Site-Konto mit einem Cloud Volumes ONTAP -System zu verknüpfen, können Sie nur aus den NSS-Konten auswählen, die der Organisation hinzugefügt wurden, deren Mitglied Sie sind.
+
Die Anmeldeinformationen auf NSS-Kontoebene unterscheiden sich von dem NSS-Konto, das mit Ihrer Anmeldung verknüpft ist.  Mit den Anmeldeinformationen auf NSS-Kontoebene können Sie Cloud Volumes ONTAP mit BYOL bereitstellen, PAYGO-Systeme registrieren und die Software aktualisieren.

+
link:task-adding-nss-accounts.html["Erfahren Sie mehr über die Verwendung von NSS-Anmeldeinformationen mit Ihrer NetApp Console-Organisation oder Ihrem NetApp Console-Konto"] .





== Verwalten Sie Ihre Benutzeranmeldeinformationen

Verwalten Sie Ihre Benutzeranmeldeinformationen, indem Sie den Benutzernamen und das Kennwort aktualisieren oder die Anmeldeinformationen löschen.

.Schritte
. Wählen Sie *Administration > Anmeldeinformationen*.
. Wählen Sie *Benutzeranmeldeinformationen*.
. Wenn Sie noch keine Benutzeranmeldeinformationen haben, können Sie *NSS-Anmeldeinformationen hinzufügen* auswählen, um Ihr NetApp Support Site-Konto hinzuzufügen.
. Verwalten Sie vorhandene Anmeldeinformationen, indem Sie im Menü „Aktionen“ die folgenden Optionen auswählen:
+
** *Anmeldeinformationen aktualisieren*: Aktualisieren Sie den Benutzernamen und das Kennwort für das Konto.
** *Anmeldeinformationen löschen*: Entfernen Sie das mit Ihrer Konsolenanmeldung verknüpfte NSS-Konto.



