---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: 'Verbinden Sie sich mit Ihren Active Directory Federation Services (AD FS), um Single Sign-On (SSO) für die NetApp Konsole zu aktivieren.  Dadurch können sich Benutzer mit ihren Unternehmensanmeldeinformationen anmelden.' 
---
= Verbinden Sie die NetApp Konsole mit Active Directory Federation Services (AD FS).
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Verbinden Sie Ihre Active Directory Federation Services (AD FS) mit der NetApp Konsole, um Single Sign-On (SSO) für die NetApp Konsole zu aktivieren.  Dadurch können sich Benutzer mit ihren Unternehmensanmeldeinformationen bei der Konsole anmelden.

.Erforderliche Rollen
Zum Erstellen und Verwalten von Föderationen ist die Rolle des Föderationsadministrators erforderlich.  Der Federation-Viewer kann die Federation-Seite anzeigen.link:reference-iam-predefined-roles.html["Erfahren Sie mehr über Zugriffsrollen."]


NOTE: Sie können eine Föderation mit Ihrem Unternehmens-IdP oder mit der NetApp -Support-Site herstellen.  NetApp empfiehlt, sich für das eine oder das andere zu entscheiden, aber nicht für beides.

NetApp unterstützt nur vom Dienstanbieter initiiertes (SP-initiiertes) SSO.  Konfigurieren Sie zunächst den Identitätsanbieter so, dass er der NetApp Konsole als Dienstanbieter vertraut.  Erstellen Sie dann mithilfe der Konfiguration Ihres Identitätsanbieters eine Verbindung in der Konsole.

Sie können eine Föderation mit Ihrem AD FS-Server einrichten, um Single Sign-On (SSO) für die NetApp Konsole zu aktivieren.  Der Vorgang umfasst die Konfiguration Ihres AD FS, sodass es der Konsole als Dienstanbieter vertraut, und die anschließende Herstellung der Verbindung in der NetApp -Konsole.

.Bevor Sie beginnen
* Es ist ein IdP-Konto mit Administratorrechten erforderlich.  Koordinieren Sie die Durchführung der Schritte mit Ihrem IdP-Administrator.
* Identifizieren Sie die Domäne, die Sie für die Föderation verwenden möchten.  Sie können Ihre E-Mail-Domäne oder eine andere Domäne verwenden, die Ihnen gehört.  Wenn Sie eine andere Domäne als Ihre E-Mail-Domäne verwenden möchten, müssen Sie die Domäne zuerst in der Konsole verifizieren.  Sie können dies tun, indem Sie die Schritte in derlink:task-federation-verify-domain.html["Überprüfen Sie Ihre Domäne in der NetApp Konsole"] Thema.


.Schritte
. Wählen Sie *Verwaltung > Identität und Zugriff*.
. Wählen Sie *Föderation* aus, um die Seite *Föderationen* anzuzeigen.
. Wählen Sie *Neue Föderation konfigurieren*.
. Geben Sie Ihre Domänendetails ein:
+
.. Wählen Sie, ob Sie eine verifizierte Domäne oder Ihre E-Mail-Domäne verwenden möchten.  Die E-Mail-Domäne ist die Domäne, die mit dem Konto verknüpft ist, mit dem Sie angemeldet sind.
.. Geben Sie den Namen der Föderation ein, die Sie konfigurieren.
.. Wenn Sie eine verifizierte Domäne auswählen, wählen Sie die Domäne aus der Liste aus.


. Wählen Sie *Weiter*.
. Wählen Sie als Verbindungsmethode *Protokoll* und dann *Active Directory Federation Services (AD FS)*.
. Wählen Sie *Weiter*.
. Erstellen Sie eine Vertrauensstellung der vertrauenden Seite auf Ihrem AD FS-Server.  Sie können PowerShell verwenden oder es manuell auf Ihrem AD FS-Server konfigurieren.  Weitere Informationen zum Erstellen einer Vertrauensstellung der vertrauenden Seite finden Sie in der AD FS-Dokumentation.
+
.. Erstellen Sie die Vertrauensstellung mithilfe von PowerShell und dem folgenden Skript:
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. Alternativ können Sie die Vertrauensstellung manuell in der AD FS-Verwaltungskonsole erstellen.  Verwenden Sie beim Erstellen der Vertrauensstellung die folgenden NetApp -Konsolenwerte:
+
*** Verwenden Sie beim Erstellen der Relying Trust Identifier den Wert **YOUR_TENANT**: `netapp-cloud-account`
*** Wenn Sie *Unterstützung für WS-Federation aktivieren* auswählen, verwenden Sie den Wert **YOUR_AUTH0_DOMAIN**: `netapp-cloud-account.auth0.com`


.. Kopieren Sie nach dem Erstellen der Vertrauensstellung die Metadaten-URL von Ihrem AD FS-Server oder laden Sie die Verbundmetadatendatei herunter.  Sie benötigen diese URL oder Datei, um die Verbindung in der Konsole herzustellen.


+
NetApp empfiehlt die Verwendung der Metadaten-URL, damit die NetApp Konsole automatisch die neueste AD FS-Konfiguration abrufen kann.  Wenn Sie die Federation-Metadatendatei herunterladen, müssen Sie sie bei jeder Änderung Ihrer AD FS-Konfiguration manuell in der NetApp -Konsole aktualisieren.

. Kehren Sie zur Konsole zurück und wählen Sie *Weiter*, um die Verbindung herzustellen.
. Stellen Sie die Verbindung mit AD FS her.
+
.. Geben Sie die *AD FS-URL* ein, die Sie im vorherigen Schritt von Ihrem AD FS-Server kopiert haben, oder laden Sie die Verbundmetadatendatei hoch, die Sie von Ihrem AD FS-Server heruntergeladen haben.


. Wählen Sie *Verbindung erstellen*.  Das Herstellen der Verbindung kann einige Sekunden dauern.
. Wählen Sie *Weiter*.
. Wählen Sie *Verbindung testen*, um Ihre Verbindung zu testen.  Sie werden zu einer Anmeldeseite für Ihren IdP-Server weitergeleitet.  Melden Sie sich mit Ihren IdP-Anmeldeinformationen an, um den Test abzuschließen, und kehren Sie zur Konsole zurück, um die Verbindung zu aktivieren.
. Wählen Sie *Weiter*.
. Überprüfen Sie auf der Seite *Föderation aktivieren* die Föderationsdetails und wählen Sie dann *Föderation aktivieren* aus.
. Wählen Sie *Fertig*, um den Vorgang abzuschließen.


Nachdem Sie die Föderation aktiviert haben, können sich Benutzer mit ihren Unternehmensanmeldeinformationen bei der NetApp Konsole anmelden.
