= 
:allow-uri-read: 


Nachdem Sie den Konsolen-Agenten installiert und eingerichtet haben, fügen Sie Ihre Cloud-Anmeldeinformationen hinzu, damit der Konsolen-Agent über die erforderlichen Berechtigungen zum Ausführen von Aktionen in AWS oder Azure verfügt.

[role="tabbed-block"]
====
.AWS
--
.Bevor Sie beginnen
Wenn Sie diese AWS-Anmeldeinformationen gerade erstellt haben, kann es einige Minuten dauern, bis sie verfügbar sind.  Warten Sie einige Minuten, bevor Sie die Anmeldeinformationen zur Konsole hinzufügen.

.Schritte
. Wählen Sie *Administration > Anmeldeinformationen*.
. Wählen Sie *Anmeldeinformationen der Organisation* aus.
. Wählen Sie *Anmeldeinformationen hinzufügen* und folgen Sie den Schritten des Assistenten.
+
.. *Speicherort der Anmeldeinformationen*: Wählen Sie *Amazon Web Services > Agent.
.. *Anmeldeinformationen definieren*: Geben Sie einen AWS-Zugriffsschlüssel und einen geheimen Schlüssel ein.
.. *Marketplace-Abonnement*: Verknüpfen Sie ein Marketplace-Abonnement mit diesen Anmeldeinformationen, indem Sie sich jetzt anmelden oder ein vorhandenes Abonnement auswählen.
.. *Überprüfen*: Bestätigen Sie die Angaben zu den neuen Anmeldeinformationen und wählen Sie *Hinzufügen*.




Sie können jetzt zu https://console.netapp.com["NetApp Console"^] um mit der Verwendung des Konsolenagenten zu beginnen.

--
.Azurblau
--
.Bevor Sie beginnen
Wenn Sie diese Azure-Anmeldeinformationen gerade erstellt haben, kann es einige Minuten dauern, bis sie verfügbar sind.  Warten Sie einige Minuten, bevor Sie die Anmeldeinformationen zum Konsolenagenten hinzufügen.

.Schritte
. Wählen Sie *Administration > Anmeldeinformationen*.
. Wählen Sie *Anmeldeinformationen hinzufügen* und folgen Sie den Schritten des Assistenten.
+
.. *Speicherort der Anmeldeinformationen*: Wählen Sie *Microsoft Azure > Agent*.
.. *Anmeldeinformationen definieren*: Geben Sie Informationen zum Microsoft Entra-Dienstprinzipal ein, der die erforderlichen Berechtigungen erteilt:
+
*** Anwendungs-ID (Client-ID)
*** Verzeichnis-ID (Mandant)
*** Client-Geheimnis


.. *Marketplace-Abonnement*: Verknüpfen Sie ein Marketplace-Abonnement mit diesen Anmeldeinformationen, indem Sie sich jetzt anmelden oder ein vorhandenes Abonnement auswählen.
.. *Überprüfen*: Bestätigen Sie die Angaben zu den neuen Anmeldeinformationen und wählen Sie *Hinzufügen*.




.Ergebnis
Der Konsolenagent verfügt jetzt über die erforderlichen Berechtigungen, um in Ihrem Namen Aktionen in Azure auszuführen.  Sie können jetzt zu https://console.netapp.com["NetApp Console"^] um mit der Verwendung des Konsolenagenten zu beginnen.

--
====