= 
:allow-uri-read: 


. Überprüfen Sie Ihre Auswahl, um zu verifizieren, dass Ihre Einrichtung korrekt ist.
+
.. Das Kästchen *Agentenkonfiguration validieren* ist standardmäßig aktiviert, damit die Konsole bei der Bereitstellung die Netzwerkverbindungsanforderungen überprüft. Schlägt die Bereitstellung des Agenten durch die Konsole fehl, wird ein Bericht zur Fehlerbehebung erstellt. Bei erfolgreicher Bereitstellung wird kein Bericht bereitgestellt.


+
[NOTE]
====
** Wenn Sie noch die link:reference-networking-saas-console-previous.html["vorherige Endpunkte"] verwendete Methode für Agenten-Upgrades nutzen, schlägt die Validierung mit einem Fehler fehl. Um dies zu vermeiden, deaktivieren Sie das Kästchen, um die Validierungsprüfung zu überspringen.
** Während der Installation prüft NetApp, ob auf dem Agent-Host mindestens 80 % des gesamten Festplattenspeichers verfügbar sind, einschließlich 48 GB in `/opt` und 32 GB in `/var` (insgesamt 80 GB). Nach der Installation müssen mindestens 20 % des gesamten Festplattenspeichers verfügbar bleiben, einschließlich 12 GB in `/opt` und 8 GB in `/var` (insgesamt 20 GB).


====

