= 
:allow-uri-read: 


Erstellen Sie eine Rolle und wenden Sie sie auf ein Dienstkonto an, das Sie für die VM-Instanz des Konsolenagenten verwenden.

.Schritte
. Erstellen Sie eine benutzerdefinierte Rolle in Google Cloud:
+
.. Erstellen Sie eine YAML-Datei, die die in derlink:reference-permissions-gcp.html["Konsolen-Agent-Richtlinie für Google Cloud"] .
.. Aktivieren Sie Cloud Shell in Google Cloud.
.. Laden Sie die YAML-Datei hoch, die die erforderlichen Berechtigungen für den Konsolenagenten enthält.
.. Erstellen Sie eine benutzerdefinierte Rolle mithilfe der `gcloud iam roles create` Befehl.
+
Das folgende Beispiel erstellt eine Rolle mit dem Namen „Agent“ auf Projektebene:

+
[source, gcloud]
----
gcloud iam roles create agent --project=myproject --file=agent.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Google Cloud-Dokumente: Erstellen und Verwalten benutzerdefinierter Rollen"^]



. Erstellen Sie ein Dienstkonto in Google Cloud:
+
.. Wählen Sie im IAM- und Admin-Dienst *Dienstkonten > Dienstkonto erstellen*.
.. Geben Sie die Details des Dienstkontos ein und wählen Sie *Erstellen und fortfahren*.
.. Wählen Sie die Rolle aus, die Sie gerade erstellt haben.
.. Schließen Sie die restlichen Schritte ab, um das Dienstkonto zu erstellen.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Google Cloud-Dokumente: Erstellen eines Dienstkontos"^]




