= 
:allow-uri-read: 


.Bevor Sie beginnen
Folgendes sollten Sie haben:

* Root-Berechtigungen zum Installieren des Agenten.
* Angaben zu einem Proxy-Server, falls für den Internetzugang vom Agenten ein Proxy erforderlich ist.
+
Sie haben die Möglichkeit, nach der Installation einen Proxyserver zu konfigurieren, hierzu ist jedoch ein Neustart des Agenten erforderlich.

* Ein von einer Zertifizierungsstelle signiertes Zertifikat, wenn der Proxyserver HTTPS verwendet oder wenn es sich bei dem Proxy um einen abfangenden Proxy handelt.


.Informationen zu diesem Vorgang
Das auf der NetApp Support-Site verfügbare Installationsprogramm ist möglicherweise eine frühere Version.  Nach der Installation aktualisiert sich der Agent automatisch, wenn eine neue Version verfügbar ist.

.Schritte
. Wenn die Systemvariablen _http_proxy_ oder _https_proxy_ auf dem Host festgelegt sind, entfernen Sie sie:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Wenn Sie diese Systemvariablen nicht entfernen, schlägt die Installation fehl.

. Laden Sie die Agentensoftware von der https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Site"^] , und kopieren Sie es dann auf den Linux-Host.
+
Sie sollten das „Online“-Agent-Installationsprogramm herunterladen, das für die Verwendung in Ihrem Netzwerk oder in der Cloud vorgesehen ist.

. Weisen Sie Berechtigungen zum Ausführen des Skripts zu.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Dabei ist <Version> die Version des Agenten, die Sie heruntergeladen haben.

. Führen Sie das Installationsskript aus.
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Die Parameter --proxy und --cacert sind optional.  Wenn Sie einen Proxyserver haben, müssen Sie die Parameter wie gezeigt eingeben.  Das Installationsprogramm fordert Sie nicht auf, Informationen zu einem Proxy anzugeben.

+
Hier ist ein Beispiel für den Befehl mit beiden optionalen Parametern:

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy konfiguriert den Agenten für die Verwendung eines HTTP- oder HTTPS-Proxyservers in einem der folgenden Formate:

+
** \http://Adresse:Port
** \http://Benutzername:Passwort@Adresse:Port
** \http://Domänenname%92Benutzername:Passwort@Adresse:Port
** \https://Adresse:Port
** \https://Benutzername:Passwort@Adresse:Port
** \https://Domänenname%92Benutzername:Passwort@Adresse:Port
+
Beachten Sie Folgendes:

+
*** Der Benutzer kann ein lokaler Benutzer oder ein Domänenbenutzer sein.
*** Für einen Domänenbenutzer müssen Sie den ASCII-Code für ein \ verwenden, wie oben gezeigt.
*** Der Agent unterstützt keine Benutzernamen oder Passwörter, die das @-Zeichen enthalten.
*** Wenn das Kennwort eines der folgenden Sonderzeichen enthält, müssen Sie dieses Sonderzeichen durch Voranstellen eines Backslashs maskieren: & oder !
+
Beispiel:

+
\http://bxpproxyuser:netapp1\!@Adresse:3128





+
--cacert gibt ein von einer Zertifizierungsstelle signiertes Zertifikat an, das für den HTTPS-Zugriff zwischen dem Agenten und dem Proxyserver verwendet werden soll.  Dieser Parameter ist nur erforderlich, wenn Sie einen HTTPS-Proxyserver angeben oder wenn es sich bei dem Proxy um einen abfangenden Proxy handelt.

. Wenn Sie Podman verwendet haben, müssen Sie den Aardvark-DNS-Port anpassen.
+
.. Stellen Sie eine SSH-Verbindung zur virtuellen Agent-Maschine her.
.. Öffnen Sie die Datei podman_/usr/share/containers/containers.conf_ und ändern Sie den gewählten Port für den Aardvark-DNS-Dienst.  Ändern Sie ihn beispielsweise in 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. Starten Sie die virtuelle Agentenmaschine neu.




. Warten Sie, bis die Installation abgeschlossen ist.
+
Am Ende der Installation wird der Agentendienst (occm) zweimal neu gestartet, wenn Sie einen Proxyserver angegeben haben.

. Öffnen Sie einen Webbrowser auf einem Host, der über eine Verbindung zur virtuellen Agent-Maschine verfügt, und geben Sie die folgende URL ein:
+
https://_ipaddress_[]

. Richten Sie nach der Anmeldung den Agenten ein:
+
.. Geben Sie die Konsolenorganisation an, die mit dem Agenten verknüpft werden soll.
.. Geben Sie einen Namen für das System ein.
.. Lassen Sie unter *Arbeiten Sie in einer sicheren Umgebung?* den eingeschränkten Modus deaktiviert.
+
Sie sollten den eingeschränkten Modus deaktiviert lassen, da diese Schritte die Verwendung der Konsole im Standardmodus beschreiben.  Sie sollten den eingeschränkten Modus nur aktivieren, wenn Sie über eine sichere Umgebung verfügen und dieses Konto von den Backend-Diensten der Konsole trennen möchten.  Wenn das der Fall ist,link:task-quick-start-restricted-mode.html["Befolgen Sie die Schritte, um mit der NetApp Console im eingeschränkten Modus zu beginnen"] .

.. Wählen Sie *Los geht's*.



