= 
:allow-uri-read: 


.Bevor Sie beginnen
Folgendes sollten Sie haben:

* Root-Berechtigungen zum Installieren des Konsolenagenten.
* Details zu einem Proxyserver, falls für den Internetzugriff vom Konsolenagenten ein Proxy erforderlich ist.
+
Sie haben die Möglichkeit, nach der Installation einen Proxyserver zu konfigurieren. Dazu muss jedoch der Console-Agent neu gestartet werden.

* Ein von einer Zertifizierungsstelle signiertes Zertifikat, wenn der Proxyserver HTTPS verwendet oder wenn es sich bei dem Proxy um einen abfangenden Proxy handelt.



NOTE: Sie können bei der manuellen Installation des Konsolenagenten kein Zertifikat für einen transparenten Proxyserver festlegen. Wenn Sie ein Zertifikat für einen transparenten Proxyserver festlegen müssen, müssen Sie nach der Installation die Wartungskonsole verwenden. Erfahren Sie mehr über die link:reference-agent-maint-console-proxy.html["Agenten-Wartungskonsole"]Die

.Informationen zu diesem Vorgang
Nach der Installation aktualisiert sich der Konsolenagent automatisch, wenn eine neue Version verfügbar ist.

.Schritte
. Wenn die Systemvariablen _http_proxy_ oder _https_proxy_ auf dem Host festgelegt sind, entfernen Sie sie:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Wenn Sie diese Systemvariablen nicht entfernen, schlägt die Installation fehl.

. Laden Sie die Console-Agent-Software herunter und kopieren Sie sie anschließend auf den Linux-Host.  Sie können es entweder von der NetApp Console oder von der NetApp -Support-Website herunterladen.
+
** NetApp Console: Gehen Sie zu *Agents > Verwaltung > Agent bereitstellen > Lokal > Manuelle Installation*.
+
Wählen Sie das Herunterladen der Agenteninstallationsdateien oder eine URL zu den Dateien.

** https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["NetApp Support Site"^] (Erforderlich, falls Sie noch keinen Zugriff auf die Konsole haben).
+

NOTE: Laden Sie den "online"-Agenten-Installer herunter, der für die Verwendung in Ihrem Netzwerk oder in der Cloud vorgesehen ist. Ein separater "offline"-Installer ist für den Console-Agenten verfügbar, aber er wird nur bei Bereitstellungen im privaten Modus unterstützt.

** NetApp Support-Website (erforderlich, falls Sie noch keinen Zugriff auf die Konsole haben) https://mysupport.netapp.com/site/products/all/details/netapp-console/downloads-tab["NetApp Support Site"^].


. Weisen Sie Berechtigungen zum Ausführen des Skripts zu.
+
[source, cli]
----
chmod +x NetApp_Console_Agent_Cloud_<version>
----
+
Dabei ist <Version> die Version des Konsolenagenten, die Sie heruntergeladen haben.

. Deaktivieren Sie bei der Installation in einer Government Cloud-Umgebung die Konfigurationsprüfungen.link:task-troubleshoot-agent.html#disable-config-check["Erfahren Sie, wie Sie Konfigurationsprüfungen für manuelle Installationen deaktivieren."]
. Führen Sie das Installationsskript aus.
+
[source, cli]
----
./NetApp_Console_Agent_Cloud_<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
Sie müssen Proxy-Informationen hinzufügen, falls Ihr Netzwerk einen Proxy für den Internetzugang benötigt. Sie können während der Installation einen expliziten Proxy hinzufügen. Die `--proxy` und `--cacert` Parameter sind optional und Sie werden nicht dazu aufgefordert, sie hinzuzufügen. Wenn Sie einen expliziten Proxyserver haben, müssen Sie die Parameter wie gezeigt eingeben.

+

NOTE: Wenn Sie einen transparenten Proxy konfigurieren möchten, können Sie dies nach der Installation tun link:reference-agent-maint-console-proxy.html["Erfahren Sie mehr über die Agentenwartungskonsole."].

+
Hier ist ein Beispiel für die Konfiguration eines expliziten Proxyservers mit einem CA-signierten Zertifikat:

+
[source, cli]
----
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
./NetApp_Console_Agent_Cloud_v4.0.0 --proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
`--proxy`Konfiguriert den Konsolenagenten zur Verwendung eines HTTP- oder HTTPS-Proxyserver mithilfe eines der folgenden Formate:

+
** \http://Adresse:Port
** \http://Benutzername:Passwort@Adresse:Port
** \http://Domänenname%92Benutzername:Passwort@Adresse:Port
** \https://Adresse:Port
** \https://Benutzername:Passwort@Adresse:Port
** \https://Domänenname%92Benutzername:Passwort@Adresse:Port
+
Beachten Sie Folgendes:

+
*** Der Benutzer kann ein lokaler Benutzer oder ein Domänenbenutzer sein.
*** Für einen Domänenbenutzer müssen Sie den ASCII-Code für ein \ verwenden, wie oben gezeigt.
*** Der Console-Agent unterstützt keine Benutzernamen oder Passwörter, die das @-Zeichen enthalten.
*** Wenn das Kennwort eines der folgenden Sonderzeichen enthält, müssen Sie dieses Sonderzeichen durch Voranstellen eines Backslashs maskieren: & oder !
+
Beispiel:

+
\http://bxpproxyuser:netapp1\!@Adresse:3128





. Wenn Sie Podman verwendet haben, müssen Sie den Aardvark-DNS-Port anpassen.
+
.. Stellen Sie eine SSH-Verbindung zur virtuellen Maschine des Konsolenagenten her.
.. Öffnen Sie die Datei podman_/usr/share/containers/containers.conf_ und ändern Sie den gewählten Port für den Aardvark-DNS-Dienst.  Ändern Sie ihn beispielsweise in 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf
----
+
Beispiel:

+
[source, text]
----
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
----
.. Starten Sie die virtuelle Maschine des Konsolenagenten neu.




. Warten Sie, bis die Installation abgeschlossen ist.
+
Am Ende der Installation wird der Konsolenagentdienst (occm) zweimal neu gestartet, wenn Sie einen Proxyserver angegeben haben.

+

NOTE: Wenn die Installation fehlschlägt, können Sie den Installationsbericht und die Protokolle anzeigen, die Ihnen bei der Behebung der Probleme helfen.link:task-troubleshoot-agent.html#troubleshoot-installation["Erfahren Sie, wie Sie Installationsprobleme beheben."]

. Öffnen Sie einen Webbrowser auf einem Host, der über eine Verbindung zur virtuellen Maschine des Konsolenagenten verfügt, und geben Sie die folgende URL ein:
+
https://_ipaddress_[]

. Richten Sie nach der Anmeldung den Konsolenagenten ein:
+
.. Geben Sie die Organisation an, die mit dem Konsolenagenten verknüpft werden soll.
.. Geben Sie einen Namen für das System ein.
.. Lassen Sie unter *Arbeiten Sie in einer sicheren Umgebung?* den eingeschränkten Modus deaktiviert.
+
Sie sollten den eingeschränkten Modus deaktiviert lassen, da diese Schritte die Verwendung der Konsole im Standardmodus beschreiben.  Sie sollten den eingeschränkten Modus nur aktivieren, wenn Sie über eine sichere Umgebung verfügen und dieses Konto von den Backend-Diensten trennen möchten.  Wenn das der Fall ist,link:task-quick-start-restricted-mode.html["Befolgen Sie die Schritte, um mit der NetApp Console im eingeschränkten Modus zu beginnen"] .

.. Wählen Sie *Los geht's*.



