= Port, der für den DNS-Weiterleitungs-Daemon mit Netavark in der Rootful-Bridge verwendet werden soll
:allow-uri-read: 


.Bevor Sie beginnen
Folgendes sollten Sie haben:

* Root-Berechtigungen zum Installieren des Konsolenagenten.
* Details zu einem Proxyserver, falls für den Internetzugriff vom Konsolenagenten ein Proxy erforderlich ist.
+
Sie haben die Möglichkeit, nach der Installation einen Proxyserver zu konfigurieren, hierzu ist jedoch ein Neustart des Konsolenagenten erforderlich.

* Ein von einer Zertifizierungsstelle signiertes Zertifikat, wenn der Proxyserver HTTPS verwendet oder wenn es sich bei dem Proxy um einen abfangenden Proxy handelt.



NOTE: Sie können bei der manuellen Installation des Konsolenagenten kein Zertifikat für einen transparenten Proxyserver festlegen. Wenn Sie ein Zertifikat für einen transparenten Proxyserver festlegen müssen, müssen Sie nach der Installation die Wartungskonsole verwenden. Erfahren Sie mehr über die link:reference-connector-maint-console.html["Agenten-Wartungskonsole"]Die

.Informationen zu diesem Vorgang
Das auf der NetApp Support-Site verfügbare Installationsprogramm ist möglicherweise eine frühere Version.  Nach der Installation aktualisiert sich der Konsolenagent automatisch, wenn eine neue Version verfügbar ist.

.Schritte
. Wenn die Systemvariablen _http_proxy_ oder _https_proxy_ auf dem Host festgelegt sind, entfernen Sie sie:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Wenn Sie diese Systemvariablen nicht entfernen, schlägt die Installation fehl.

. Laden Sie die Console-Agent-Software von der https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp Support Site"^] , und kopieren Sie es dann auf den Linux-Host.
+
Sie sollten das „Online“-Agent-Installationsprogramm herunterladen, das für die Verwendung in Ihrem Netzwerk oder in der Cloud vorgesehen ist.

. Weisen Sie Berechtigungen zum Ausführen des Skripts zu.
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
Dabei ist <Version> die Version des Konsolenagenten, die Sie heruntergeladen haben.

. Führen Sie das Installationsskript aus.
+
[source, cli]
----
./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>

+
You'll need to add proxy information if your network requires a proxy for internet access. You can add either a transparent or explicit proxy. The --proxy and --cacert parameters are optional and you won't be prompted to add them. If you have a proxy server, you will need to enter the parameters as shown.
+
Here is an example configuring an explicit proxy server with a CA-signed certificate:
+
[source,cli]
----


[listing]
----
+
--proxy configures the Console agent to use an HTTP or HTTPS proxy server using one of the following formats:
+
* \http://address:port
* \http://user-name:password@address:port
* \http://domain-name%92user-name:password@address:port
* \https://address:port
* \https://user-name:password@address:port
* \https://domain-name%92user-name:password@address:port
+
Note the following:
+
** The user can be a local user or domain user.
** For a domain user, you must use the ASCII code for a \ as shown above.
** The Console agent doesn't support user names or passwords that include the @ character.
** If the password includes any of the following special characters, you must escape that special character by prepending it with a backslash: & or !
+
For example:
+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert specifies a CA-signed certificate to use for HTTPS access between Console agent and the proxy server. This parameter is required for HTTPS proxy servers, intercepting proxy servers, and transparent proxy servers.

+
Here is an example configuring a transparent proxy server. When you configure a transparent proxy, you don't need to define the proxy server. You only add a CA-signed certificate to your Console agent host:

+
[source,cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
[listing]
----
. If you used Podman, you'll need to adjust the aardvark-dns port.
.. SSH to the Console agent virtual machine.
.. Open podman _/usr/share/containers/containers.conf_ file and modify the chosen port for Aardvark DNS service. For example, change it to 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf

[listing]
----
+
For example:
+
[source,text]
----


= Port, der für den DNS-Weiterleitungs-Daemon mit Netavark in der Rootful-Bridge verwendet werden soll



= Modus und DNS aktiviert.



= Die Verwendung eines alternativen Ports kann hilfreich sein, wenn andere DNS-Dienste ...



= Auf der Maschine ausführen.

# dns_bind_port = 54

[listing]
----
.. Reboot the Console agent virtual machine.
//end::main-steps[]

//tag::standard-mode-steps-for-cloud[]
. Wait for the installation to complete.
+
At the end of the installation, the Console agent service (occm) restarts twice if you specified a proxy server.

. Open a web browser from a host that has a connection to the Console agent virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Console agent:
.. Specify the organization to associate with the Console agent.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use the Console in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with the NetApp Console in restricted mode].
.. Select *Let's start*.

//end::standard-mode-steps-for-cloud[]
----