= 
:allow-uri-read: 


Abhängig von Ihrem Betriebssystem ist vor der Installation des Agenten entweder Podman oder Docker Engine erforderlich.

* Podman wird für Red Hat Enterprise Linux 8 und 9 benötigt.
+
<<podman-versions,Sehen Sie sich die unterstützten Podman-Versionen an>> .

* Für Ubuntu ist Docker Engine erforderlich.
+
<<podman-versions,Anzeigen der unterstützten Docker Engine-Versionen>> .



.Schritte
[role="tabbed-block"]
====
.Podman
--
Podman installieren und konfigurieren:

* Aktivieren und starten Sie den Dienst podman.socket
* Installieren Sie Python3
* Installieren Sie das entsprechende podman-compose-Paket
* Fügen Sie podman-compose zur Umgebungsvariablen PATH hinzu
* Stellen Sie sicher, dass Ihre Podman-Version Netavark Aardvark DNS anstelle von CNI verwendet.



NOTE: Passen Sie den Aardvark-DNS-Port (Standard: 53) nach der Installation des Agenten an, um DNS-Portkonflikte zu vermeiden.  Befolgen Sie die Anweisungen zum Konfigurieren des Ports.

.Schritte
. Entfernen Sie das Podman-Docker-Paket, falls es auf dem Host installiert ist.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Installieren Sie Podman.
+
Podman kann aus den Red Hat Enterprise Linux-Repositories bezogen werden.

+
Für Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Dabei ist <Version> die unterstützte Version von Podman, die Sie installieren. <<podman-versions,Sehen Sie sich die unterstützten Podman-Versionen an>> .

+
Für Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Dabei ist <Version> die unterstützte Version von Podman, die Sie installieren. <<podman-versions,Sehen Sie sich die unterstützten Podman-Versionen an>> .

. Aktivieren und starten Sie den Dienst podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Installieren Sie python3.
+
[source, cli]
----
sudo dnf install python3
----
. Installieren Sie EPEL, um podman-compose zu erhalten.
+
.. Bei Verwendung von Red Hat Enterprise 9:
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----


. Installieren Sie das Podman-Compose-Paket 1.5.0.
+
[source, cli]
----
sudo dnf install podman-compose-1.5.0
----
+
.. Bei Verwendung von Red Hat Enterprise Linux 8:
+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----


. Installieren Sie das Podman-Compose-Paket 1.0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Verwenden des `dnf install` Der Befehl erfüllt die Anforderung zum Hinzufügen von „podman-compose“ zur Umgebungsvariablen PATH.  Der Installationsbefehl fügt podman-compose zu /usr/bin hinzu, das bereits im `secure_path` Option auf dem Host.

. Wenn Sie Red Hat Enterprise Linux 8 verwenden, überprüfen Sie, ob Ihre Podman-Version NetAvark mit Aardvark DNS anstelle von CNI verwendet.
+
.. Überprüfen Sie, ob Ihr Netzwerk-Backend auf CNI eingestellt ist, indem Sie den folgenden Befehl ausführen:




[listing]
----
podman info | grep networkBackend
----
. Wenn das Netzwerk-Backend auf `CNI` , müssen Sie es ändern in `netavark` .
. Installieren `netavark` Und `aardvark-dns` mit dem folgenden Befehl:


[listing]
----
dnf install aardvark-dns netavark
----
. Öffnen Sie die `/etc/containers/containers.conf` Datei und ändern Sie die Option network_backend, um „netavark“ anstelle von „cni“ zu verwenden.
+
Wenn `/etc/containers/containers.conf` nicht vorhanden ist, nehmen Sie die Konfigurationsänderungen vor, um `/usr/share/containers/containers.conf` .

+
.. Starten Sie Podman neu.




[listing]
----
systemctl restart podman
----
. Bestätigen Sie mit dem folgenden Befehl, dass networkBackend jetzt in „netavark“ geändert wurde:


[listing]
----
podman info | grep networkBackend
----
--
.Docker-Engine
--
Befolgen Sie die Dokumentation von Docker, um Docker Engine zu installieren.

.Schritte
. https://docs.docker.com/engine/install/["Installationsanweisungen von Docker anzeigen"^]
+
Installieren Sie eine unterstützte Docker Engine-Version, indem Sie die folgenden Schritte befolgen. Installieren Sie nicht die neueste Version, da die Konsole diese nicht unterstützt.

. Stellen Sie sicher, dass Docker aktiviert und ausgeführt wird.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====